### ISSUE TITLE
Config with mix of declarative config files and legacy config files should assert

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#103]
While creating a target with the declarative config system during Toronto miki meetup.

We had 
* `targets.js` with a single entry under test
* `tasks.js` was just an empty file
* no `targets.json` or `tasks.json`
* we did not delete the legacy `rules.nools.js` file

Observed: This was a weird config state where some files are legacy and some are declarative. We ended up in some sort of frankenbuild where declarative targets appear but without any metrics appearing.

Expected: Would be great if medic-conf asserted for this case.

**Comment by alxndrsn** [comment]
Thanks for the report.  What would you expect `medic-conf` to do in this situation?

**Comment by kennsippell** [comment]
```      throw new Error('Both legacy and current nools definitions found.  ' +
          `You should either have ${legacyNoolsPath} or ${CURRENT_NOOLS_FILES} files.`);```

You understood the situation.

**Comment by kennsippell** [comment]
This was not address for contact-summary's legacy vs declarative files.

**Comment by kennsippell** [comment]
No AT necessary.
