### ISSUE TITLE
AppliesToType is not respected for report-based targets

### ISSUE THREAD

**Issue by newtewt** [medic/medic-conf#104]
Using the `appliesToType` prop on a target does not filter forms based on the `appliesToType`. Looking at emit there is no check for `appliesToType`. When the targets run it will iterate over every report available to the user and additional checks need to be added to `passesIf` or `appliesIf` to filter those out. 

## Repro Steps

1. Create multiple targets. 
2. Add a console.log() to a target that has an `appliesToType`.
3. Generate multiple reports of different types
4. View the console and see that your console.log statement is being shown for each report and not the one specified in `appliesToType`

https://github.com/medic/medic-conf/blob/a1303fcc62a5dc3a7592e1ea7251d9ebba6ea319/src/nools/lib.js#L148-L164

**Comment by alxndrsn** [comment]
This specifically refers to report-based targets.

**Comment by alxndrsn** [comment]
Report-based tasks also do not use `appliesToType`.  Is this feature wanted for a specific project?

**Comment by newtewt** [comment]
Looking at the code the contact targets have a check for appliesToType however the report target doesn't.  `if(c.contact && target.appliesToType.indexOf(c.contact.type)`

The documentation below on targets describes what appliesToType should do. Not project related I assume it was a miss in functionality when we were creating. 

https://github.com/medic/medic-docs/blob/master/configuration/declarative-config.md#target-properties

**Comment by kennsippell** [comment]
@ngaruko Can you confirm that this is already fixed in the latest medic-conf version?

**Comment by ngaruko** [comment]
@kennsippell ... The code has been refactored from https://github.com/medic/medic-conf/blob/a1303fcc62a5dc3a7592e1ea7251d9ebba6ea319/src/nools/lib.js#L148-L164 
to https://github.com/medic/medic-conf/blob/master/src/nools/lib.js , with check for `appliesToType` in both `task-emitter.js` and `target-emitter.js`.
LGTM.
