### ISSUE TITLE
Allow defining extra Task action content in default nools lib

### ISSUE THREAD

**Issue by derickl** [medic/medic-conf#106]
From https://github.com/medic/medic-conf/blob/c57649c246d106068ab009676c053c3cc9b6b0a2/src/nools/lib.js#L125-#L136, a task's action content only has the `source`, `source_id` and `contact` properties set.

In most of our projects, we need to pass extra data along to the follow up task e.g the current follow up count, type of follow up (e.g treatment only, referral only or treatment plus referral). These values are derived from the source report. 

Here's an example from lg-uganda (using old-style config) https://github.com/medic/medic-projects/blob/master/lg-uganda/rules.nools.js#L1609-#L1622.

**Comment by derickl** [comment]
@alxndrsn looking to see if we can bump this up the queue :)

**Comment by alxndrsn** [comment]
Fixed in `1.18.13`: add `modifyContent: function(r, content) { ... }` to task action definitions to add, remove or change the `content` section of an action.
