### ISSUE TITLE
Add default `resolvedIf` function for tasks

### ISSUE THREAD

**Issue by abbyad** [medic/medic-conf#107]
From trainings it has been noted that it would be helpful to have a default `resolvedIf` function for tasks. For mobile app projects tasks are typically resolved if the task's primary action form is submitted within the task window. Using that as the default would be useful. 

Making the default function accessible (eg Nootils) would also be useful when additional conditions are to be added. Eg Resolve if action form was submitted in windows, **or** if there is a newer pregancy.

**Comment by kennsippell** [comment]
Candidate that I used today. Needs to be a bit more generic + some unit tests.

```
const defaultResolvedIf = function (contact, report, event, dueDate) {
  const resolvingForm = this.definition.actions[0].form;
  return Utils.isFormSubmittedInWindow(
    contact.reports,
    resolvingForm,
    Utils.addDate(dueDate, -event.start).getTime(),
    Utils.addDate(dueDate, event.end + 1).getTime()
  );
};
```

**Comment by kennsippell** [comment]
Would also be nice for cases where the default is not appropriate, how can the default still be available somehow?

`resolvedIf: (contact, report, event, dueDate) => myLogic && Utils.defaultResolvedIf(contact, report, event, dueDate)`

or

`resolvedIf: function (contact, report, event, dueDate) { return myLogic && this.default(contact, report, event, dueDate); }`

or whatever

**Comment by mrjones-plip** [comment]
I was working [through our docs](https://docs.communityhealthtoolkit.org/apps/tutorials/tasks/#1-define-the-task) and chatting with @abbyad on this. We both agree this improvement would be most welcome!! :+1:

**Comment by abbyad** [comment]
Ya, it is a common source of errors for task building, and most workflows could and should use the default as it would be most intuitive to an end-user. Deviating from it should be done cautiously and with very good reason.

**Comment by kennsippell** [comment]
@abbyad Have you looked across production apps to validate this assumption with users? It sounds like a nice ideal, but is that what users want? In the existing cht-core reference app, ~4of8 would use the default (only if we also fix https://github.com/medic/medic-conf/issues/280). Looking at a config like PiH, ~11of24 tasks would use it. Muso appears to be much lower.  Not intending to nitpick, it would certainly be a convenience.

**Comment by abbyad** [comment]
Yes, it is an ideal, and I think we can get there with good defaults and better communicating best practices in workflow design.

**Comment by binokaryg** [comment]
Some questions:
1. Do we want to make `resolvedIf` optional?
2. Where do we want to make the default accessible:
    * `this.defaultResolvedIf`
    * `Utils.defaultResolvedIf`
 3. In the default, do we also want to check for the possibility that a task source report could resolve itself? (the source form and the resolving form are the same and both are within the same task window)

**Comment by abbyad** [comment]
Here are my thoughts, but open to discussion:

> 1. Do we want to make resolvedIf optional?

Yes, I would think so to simplify the creation of tasks.

> 2. Where do we want to make the default accessible:

Whichever way that is most consistent with CHT and JS standards. Do you have a preference based on what you've seen and used?

> 3. In the default, do we also want to check for the possibility that a task source report could resolve itself? (the source form and the resolving form are the same and both are within the same task window)

Good point, and the way we have solved that in some workflows is to [exclude the current report](https://github.com/medic/cht-core/blob/0280e8caa08a2b7c65958b30d2ee8eb9dc1f7d60/config/default/nools-extras.js#L40-L55) so that a report can generate tasks for another submission of the same form. It is worth including this scenario as part of the user acceptance tests and code tests.

**Comment by binokaryg** [comment]
> Do you have a preference based on what you've seen and used?

I think `Utils` could be the preferred choice as we already have most of the helper functions [there ](https://github.com/medic/medic-nootils/blob/master/src/nootils.js)already.

**Comment by kennsippell** [comment]
Rule of thumb with defaults is to target the majority case with default behavior that is natural and intuitive.

1. Yes, I'd expect this to be optional now
2. `this.defaultResolvedIf()` with proper binding and parameter piping seems intuitive. perhaps internally it uses Utils?
3. By convention, we normally look at reports created after the triggering report. So `> reported_date`

**Comment by binokaryg** [comment]
As discussed with @kennsippell, we are skipping the changes in `medic-nootils`, so `Utils.resolvedIf` is not supported.
The `resolvedIf` section is now optional and the default method will also be available as `this.defaultResolvedIf`.

PR: #392 
Docs PR: medic/cht-docs#466

**Comment by binokaryg** [comment]
This issue is ready for AT with this [PR](https://github.com/medic/medic-conf/pull/392).

**Comment by ngaruko** [comment]
LGTM - Tested against `cht-core/master`. Using options: `kipped` and `this. defaultResolvedIf`... One question though @binokaryg . If I delete all the code in `task-dafults.js`, I still get a `success` response in `medic-conf`.  Same if I rename the ` defaultResolvedIf` module therein. Maybe we need some checks to verify that the `task-dafults.js` is configured 'properly' and doing the 'right stuff'. What do you think?

**Comment by binokaryg** [comment]
Thanks, @ngaruko.
I think `task-defaults.js` is supposed to be a part of `medic-conf` source and not intended to be configured by the users. If users somehow edit it in the source, they are expected to run the unit tests which should fail if the module is not available.

**Comment by ngaruko** [comment]
Thanks @binokaryg . Then it is good to go. Feel free to merge .
