### ISSUE TITLE
Declarative config - Task "events.start" parameter off-by-one discrepancy

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#108]
Given a task with `events` configuration with fixed `dueDate` similar to this:

```    events: [
      {
        id: 'follow-up-without-danger-sign',
        start: 4,
        end: 7,
        dueDate: function(report) {
          return new Date(report.fields && 
            report.fields.danger_signs &&
            report.fields.danger_signs.next_follow_up);
        },
      },
    ],
```

Set start to `10` and navigate to the "Tasks" tab within the WebApp.
I can see hypothetical task there and the due date in the webapp UI is displayed as "due in 4 days".
Now change `start: 4` 

The task is filtered out and no longer displays. This appears to be an off-by-one error.

toronto-mini-meetup

**Comment by alxndrsn** [comment]
@kennsippell thanks for the report.  Are you able to test in a different timezone?  Checking with something in the Eastern hemisphere, or `GMT` would both be helpful.

**Comment by kennsippell** [comment]
Cannot be reproduced
