### ISSUE TITLE
Support for ES6 in declarative config

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#109]
jslint in medic_conf when analysing the generated code for nools rules doesn't allowing ES6.
Seems like ES6 is used in webapp now, so should be able to safely lift this restriction in medic-conf also.

For example, a lambda in tasks.js yields
`line 103, col 49, 'arrow function syntax (=>)' is only available in ES6 (use 'esversion: 6'). (W119)`

toronto-mini-meetup

**Comment by alxndrsn** [comment]
This is deliberate - not all clients can run ES6 code.

**Comment by newtewt** [comment]
Reopening - there is more push to get es6 support and latest android wrapper has a version that supports it. May need some conditioning for older projects that may have not updated.

**Comment by derickl** [comment]
@newtewt we should only do this once ALL projects are on 3.x

**Comment by kennsippell** [comment]
Projects don't actually need 3.x, but rather they need the latest android container.  Definitely a concern.

I see two options:

1. We could have an `--allow-es6` flag on medic-conf which changes the rules which are enforced.
1. We could do a major version bump of medic-conf and projects on the old container just use `medic-conf 1.x`.

**Comment by garethbowen** [comment]
I like the flag idea concept though it might be better to have a property defined in the project configuration somewhere that way you wouldn't forget to include it.

The problem with the version bump is if a TL is working on two projects it's a pain to have to keep changing your medic-conf version.

**Comment by dianabarsan** [comment]
Ready for AT on `109-es6`.

**Comment by ngaruko** [comment]
The `medic-conf` repo has a mixture of es6 and es5 code. We also have a high level (repo-level) `.eslintrc`  file  with an  `ecmaVersion` version ( `"ecmaVersion": 8`)  that is different  from subfolder-level `.eslintrc` files like in `nools` (`"ecmaVersion": 5`).
Is this intentional @kennsippell ?

**Comment by kennsippell** [comment]
@ngaruko Yep! The file in the root folder controls the code that runs `medic-conf` itself, which supports es8. The code in the `nools` and `contact-summary` folders runs inside the webapp and so is limited to es5 (to maintain backward compatibility for partners without the latest android app). Partners can override it via their own `.eslintrc` to support es6 (default for new projects).

**Comment by ngaruko** [comment]
Thanks @kennsippell . Ready to close. The [branch](https://github.com/medic/medic-conf/pull/215) has conflicts though, could you please have a look and resolve those?
