### ISSUE TITLE
medic-conf --instance {project-url-prefix} renders the instance in 502 status

### ISSUE THREAD

**Issue by mukesh2006** [medic/medic-conf#116]
Instance: [http://bss-in.app.medicmobile.org/](http://bss-in.app.medicmobile.org/)

Steps to produce:
- `medic-conf compile-app-settings`: No error
- `medic-conf --instance  bss-in.app` : It gives the following error:

```
Conversion complete!
INFO convert-contact-forms complete.
INFO Starting action: backup-all-forms…
ERROR FetchError: invalid json response body at https://bss-in.app.medicmobile.org/medic/ reason: Unexpected token < in JSON at position 0
    at C:\Users\mukes\AppData\Roaming\npm\node_modules\medic-conf\node_modules\node-fetch\lib\index.js:241:32
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

After this `error`, the instance starts 502ing, and I'm unable just to upload the `app_settings.json` using the command `medic-conf --instance  bss-in.app upload-app-settings` fails with following error:

```
INFO Starting action: upload-app-settings…
ERROR StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.9.11</center>\r\n</body>\r\n</html>\r\n"
    at new StatusCodeError (C:\Users\mukes\AppData\Roaming\npm\node_modules\medic-conf\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\mukes\AppData\Roaming\npm\node_modules\medic-conf\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\mukes\AppData\Roaming\npm\node_modules\medic-conf\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\mukes\AppData\Roaming\npm\node_modules\medic-conf\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\mukes\AppData\Roaming\npm\node_modules\medic-conf\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\mukes\AppData\Roaming\npm\node_modules\medic-conf\node_modules\request\request.js:1083:12)
``` 

@alxndrsn @SCdF @abbyad

**Comment by dianabarsan** [comment]
@mukesh2006 This happens when uploading `standard` config from medic-mobile `master` onto a `2.18` instance?

**Comment by alxndrsn** [comment]
Can this be closed, or would it be helpful if `medic-conf` detected this issue and prevented upload of incompatible config?

**Comment by abbyad** [comment]
@dianabarsan the issue you quoted is 3.4, whereas the original issue is about upgrading to 2.18. Is there another issue related to this one?

**Comment by dianabarsan** [comment]
@abbyad the issue was about installing the `standard` config from `master` (3.4 which includes the change) onto a 2.18 instance.

**Comment by dianabarsan** [comment]
This is the related issue from medic-projects:
https://github.com/medic/medic-projects/issues/5469#issuecomment-443117154

**Comment by abbyad** [comment]
Ah, thanks for clarifying.

Projects are still pointing to master, although we coincidentally discussed this last week with some teammates to make sure Standard projects point to a released version of the Standard config in their package.json:
```
        "dependencies": {
          "medic": "git@github.com:medic/medic-webapp.git#3.2.x"
        },
```

Follow up documentation is coming from that discussion.

**Comment by mukesh2006** [comment]
I think it will be helpful if `medic-conf` detected this issue and prevented uploading incompatible config. @abbyad @alxndrsn

**Comment by SCdF** [comment]
NB: we have, buried in git history a (incomplete and partially incorrect) settings schema in `kanso.json:settings_schema`.

My 2c is that we should dredge that up, correct it, and ship it in api. Then medic-conf doesn't need to know what version you're pushing to, and api can validate your config against the correct schema.

**Comment by garethbowen** [comment]
Here's the issue to "dredge that up": medic/medic-webapp#4783
