### ISSUE TITLE
Bulk user import

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-conf#117]
Creating users has become quite complex, as you need...
- a doc in the _users db
- a user-settings doc in the medic db
- a contact to associate with the user (optional but wanted most often)
- a facility to assign the user to (optional but wanted most often)

This is really annoying when [creating a bunch of users](https://github.com/medic/medic-projects/issues/70).

Create a bulk import command so it's easy for an admin to upload a file and have all required documents created on the server.

While there it may make sense to implement a user export, but the export wouldn't be able to have the password, so make sure you handle this case without overwriting existing user's passwords.

**Comment by garethbowen** [comment]
Assigning Nick as he thinks this is already doable.

**Comment by newtewt** [comment]
This is achievable using create-users in medic-conf.

Here's a sample CSV incase you need to see how it's structured. 
https://docs.google.com/spreadsheets/u/1/d/17iLe_zht1tMo3Ml63zPdjfvF5e0Gxgg5m-bJcpTKsEk/edit?usp=drive_web&ouid=113141968914756132272
