### ISSUE TITLE
Improve medic-conf testing by using actual form definitions

### ISSUE THREAD

**Issue by SCdF** [medic/medic-conf#128]
Our existing testing of tasks, targets, the contact summary and [soon hopefully sql](https://github.com/medic/medic-webapp/issues/5134) does not take into account the real form definitions used by that project.

When writing a test, we are hard-coding the JSON structure into those tests. This means that if the form definition changes (e.g., `fields.patient_age` gets renamed to `fields.age`) our tests still pass.

We should look into closing this gap, presumably by defining our test data in some way that would break if the forms changed in such a way that would break them.

The very easy end of this idea would be to define XPath keys and values instead of JSON, as well as some optional JSON overrides (e.g. so you can define the reported_date and other things that are not directly entered into the Enketo form), and have the test attempt to bind those keys to the configured forms.

**Comment by newtewt** [comment]
@kennsippell  has put some effort into this for Muso. Hopefully we can use that for this. 

https://github.com/medic/medic-projects/blob/muso-declarative/muso_declarative/harness

https://medic.slack.com/archives/CBDHSGQ8L/p1551094150004700

**Comment by kennsippell** [comment]
The details of the harness are now documented at https://htmlpreview.github.io/?https://raw.githubusercontent.com/medic/medic-conf-test-harness/blob/master/out/index.html

**Comment by garethbowen** [comment]
@kennsippell How's this issue going? The PR is merged and there hasn't been any update since July?

**Comment by kennsippell** [comment]
I've been tracking status and fixes through the medic-conf-test-harness repository and left this ticket open as a top-level issue. 

You can see bugs and fixes here: https://github.com/medic/medic-conf-test-harness/commits/master

I have one more change id like to make in the 3.7 timeframe to support some CHT ref app tests for one broken form. I can open a new issue for that separately and close this for 3.7? The new issue can be safely punted to 3.8 as an improvement for the CHT ref app.

@newtewt - ive have been fixing issues related to the CHT ref app and testing changes with binod and muso. Seems like good AT to me, but up to you if youd like to do more!

**Comment by newtewt** [comment]
I think that's fine. I'm going to run through the docs myself to get it setup on my machine and understand how it works from a hands on point of view.

**Comment by newtewt** [comment]
@kennsippell  I'm having some trouble filling in a text area with the `on` form. 

```
newtewt@newtewt-ubuntu:~/dev/medic-webapp/config/standard$ mocha test.spec.js 


  Getting started tests
Harness Loading form app/on...
Harness log Data node: /*/meta/deprecatedID with null-based index: undefined not found. Ignored.
    ✓ on can be loaded (104ms)
Harness Loading form app/on...
Harness log Data node: /*/meta/deprecatedID with null-based index: undefined not found. Ignored.
Harness Filling 1 pages with answer: [["yes","this is a note"]]
Harness log FormFiller Filling in 1 pages.
Harness log FormFiller Answering 2 questions.
    1) unit test confirming no pnc followup
Harness Closing harness


  1 passing (358ms)
  1 failing

  1) Getting started tests
       unit test confirming no pnc followup:
     Error: Evaluation failed: No input field found within question
      at ExecutionContext._evaluateInternal (node_modules/puppeteer/lib/ExecutionContext.js:122:13)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
    -- ASYNC --
      at ExecutionContext.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at DOMWorld.evaluate (node_modules/puppeteer/lib/DOMWorld.js:112:20)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
    -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at Page.evaluate (node_modules/puppeteer/lib/Page.js:833:43)
      at Page.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at Harness.fillForm (node_modules/medic-conf-test-harness/src/harness.js:215:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

```

**Comment by kennsippell** [comment]
Thanks @newtewt? Would you provide your test code also?

**Comment by newtewt** [comment]
@kennsippell  here you go. 

```
const { expect } = require('chai');

const Harness = require('medic-conf-test-harness');
const harness = new Harness({ verbose: true });

describe('Getting started tests', () => {
  before(async () => { return await harness.start(); });
  after(async () => { return await harness.stop(); });
  beforeEach(async () => { return await harness.clear(); });
  afterEach(() => { expect(harness.consoleErrors).to.be.empty; });

  const formName = 'on';
  it(`${formName} can be loaded`, async () => {
    await harness.loadForm(`app/${formName}`);
    expect(harness.state.pageContent).to.include(`id="${formName}"`);
  });

  it('unit test confirming no pnc followup', async () => {
    // Load the pnc_followup form and fill in 'no' on the first page and 'no' on the second page
    const result = await harness.fillForm('app/on', ['yes','this is a note'],);
    
    console.log(result);
    // Verify that the form successfully got submitted
    expect(result.errors).to.be.empty;
  
    // Verify some attributes on the resulting report
    expect(result.report.fields).to.deep.include({
      patient_name: 'Patient Name',
      s_pnc_visits: {
        s_pnc_visit: 'no',
        s_pnc_planned_date_show: '',
        s_pnc_date_show: '',
      },
      next_pnc: {
        s_next_pnc: 'no',
        next_pnc_date: '',
      }
    });
  });
});
```

**Comment by kennsippell** [comment]
Thanks @newtewt. Fixed this via https://github.com/medic/medic-conf-test-harness/commit/3ed78c116a1798c792930147e88fabe2bfce3d7c. Can you try now with medic-conf-test-harness@0.1.11?

**Comment by newtewt** [comment]
That's working well for me. At this point I'm closing and we can follow our normal flow for new issues.
