### ISSUE TITLE
Shell completion for supported actions not working

### ISSUE THREAD

**Issue by eljhkrr** [medic/medic-conf#132]
1. Enable tab completion as descried [here](https://github.com/medic/medic-conf#bash-completion).
2. Type the the `medic-conf` command and press the tab key to get command completion.

Expected:
Supported actions available in `medic-conf` should be displayed.

Actual:
`medic-conf` supported actions are not displayed.

**Comment by ngaruko** [comment]
LGTM
Autocomplete works (`Tab` key twice). Tested with ` medic-conf --version 1.20.1`

![image](https://user-images.githubusercontent.com/6979995/56639330-1d4a5f00-6679-11e9-8329-b14085656902.png).
Will close this, there is no PR to merge in `medic`
