### ISSUE TITLE
Declarative Config - subtitle_translation_key should not be a required field for all targets

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#138]
Currently the target `subtitle_translation_key` is required for all targets. Based on Muso's design spec, the subtitle is not required for any target.

**Comment by abbyad** [comment]
According to the documentation [`subtitle_translation_key` is not meant to be required](https://github.com/medic/medic-docs/blob/a6fd1b68f49d1675c3d7ff00309ba001788dd470/configuration/developing-community-health-applications.md#target-properties), so nice catch!

**Comment by newtewt** [comment]
@kennsippell  good on this one too.

**Comment by newtewt** [comment]
@kennsippell feel free to close this one.
