### ISSUE TITLE
Declarative Config - Allow data sharing and definition self-reference through the this keyword

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#139]
The declarative configuration system introduces a lot more constraints on the scoping of data.

For example, check out how `nools.rules` calculates this t_follow_up_count. It calculates a variable while emitting a task for each event. Data used to emit each task is shared with the logic to modify the task's content.
https://github.com/medic/medic-projects/blob/master/muso/rules.nools.js#L591

We can't do that anymore in declarative because there is no way to scope a variable like this anymore. The `modifyContent` function needs to handle this independently. Which is hard.

This scoping of data constraint also results in a lot more recalculations, since both appliesIf, resolvesIf, dueDate, etc all need to function as an atomic logic block with poor data sharing between them.

I'm proposing that we introduce the `this` keyword onto all declarative function code. By sharing a sort of "context" between functions of the same task/target, we can facilitating primitive data sharing. 

This could also allow for functions to reference the definition of the task/targets (eg `this.definition.events`). This reduces the amount of data which needs to be abstracted into the `nools-extras` file and allows our code layout to remain more "declarative."

**Comment by newtewt** [comment]
@kennsippell  this seems to be the same for anywhere it is referenced now. Feel free to close

**Comment by kennsippell** [comment]
Merged!
