### ISSUE TITLE
Declarative Config - Multiple tasks emitted for the same report do not have a unique id

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#140]
Given two tasks which always apply:
```
{
  name: 'a',
  appliesTo: 'report',
  appliesIf: () => true,
}
```

```
{
  name: 'b',
  appliesTo: 'report',
  appliesIf: () => true,
}
```

Expected: Two tasks to appear for each report
Observed: One task appears

This is because the id of the emitted task is not unique and is deduplicated in webapp. The name of the schedule is not included in the task's id for tasks with `appliesTo: 'report'`

**Comment by kennsippell** [comment]
Current calculation `_id: r ? (r._id + '-' + event.id) : (c.contact._id + '-' + schedule.id),`

**Comment by abbyad** [comment]
The event id is missing, so the problem seems to be that you were able to build the config missing the required `tasks.events[n].id`, as in #141. 

I think we should close this issue in favor of having smarter defaults, which take into account the task and the event, which may be covered by #141.

**Comment by kennsippell** [comment]
Even with smart defaults, we still need to include the event.id in the task's id. This is working properly when !!r but isn't included in the id when !r. I believe #140 is a separate issue.

**Comment by abbyad** [comment]
If the emitted task's ID includes the anchor doc id (eg a contact or report) along with the task and event indexes then I don't see how the `tasks[x].name` or `tasks[x].events[y].id` are used in the app. The only value I see are for debugging purposes and conversationally referring to a task.

**Comment by newtewt** [comment]
@kennsippell  I'm seeing the tasks for each report being displayed. Looks good. Feel free to close.
