### ISSUE TITLE
Declarative Config - Tasks.events[n].id should not be required

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#141]
The `tasks.events[n].id` is documented as being required. In most cases, users just want the ID to be a unique value. A smart default for the event's id could be the index of the event. This would mean that tasks.events[n].id is not required.

Currently, there is no enforcement that this value is defined. This results in tasks being emitted with `undefined` in the id, which is not unique and results in obscure failure patterns. If we don't define a smart default, we should enforce that this value is defined.

**Comment by abbyad** [comment]
Having smarter defaults would make this field irrelevant. In the meantime though, this field should be enforced as required, otherwise you can have the issue described in #140.

**Comment by kennsippell** [comment]
This just ended up being a documentation change. Addressing in https://github.com/medic/medic-docs/pull/86
