### ISSUE TITLE
Declarative Config - emitCustom should be passed in the instance which would have been emitted

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#144]
Currently targets which use the `emitCustom` function only use part of the declarative inputs. The values of `appliesTo`, `appliesIf`, and part of the data in `events` are respected and used in deciding when `emitCustom` should be invoked. However, the rest of the data in the declarative definition are ignored.  This is inconsistent and confusing.

It would be a much more useful function if the fully realized instance which _would have been emitted_ by the declarative configuration were passed into the emitCustom function. This gives the author the flexibility to adjust the output or emit multiple outputs, but they don't have to implement a bunch of logic typically handled by the declarative system.

Example of a multiple-output emitCustom:
```
emitCustom: (contact, report, instance) => {
  emitTargetInstance(instance);

  emitTargetInstance({
    _id: `${report._id}-protocol-error-count`,
    deleted: false,
    type: 'protocol-error-count',
    pass: instance.pass,
    date: instance.date,
  });
}
```

**Comment by newtewt** [comment]
@kennsippell  👍   👍   👍   👍  looks good.
