### ISSUE TITLE
Declarative Config - Support for target.idType to return the id of the parent

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#145]
Muso has the following target:

Number of Home visit 
```count distinct # of home_visit_uuid  only 1 home_visit per day per family```

This needs to inspect all reports for each `clinic` and emit the clinic's id.
It also needs to inspect all reports for each `contact` and emit the contact's parent's id (clinic).
The webapp de-dupes the emitted instances with identical ids.

We could either guess the use-cases that user need and add something like `idType: 'parent'` or we could give them robust tools which allow them to define what they need by making idType support a function which can return the id based on any calculation.

**Comment by garethbowen** [comment]
Having an id generator function sounds good to me but it's a little risky. The important thing is that it must be immutable otherwise you get some really annoying bugs. It would be safer (but less flexible) to have an array of property names to base the ID on, eg: `id: [ "visit", "{parent}" ]` (better syntax required).

**Comment by kennsippell** [comment]
@garethbowen I do see merits in the "safer" approach suggested above. Generally, I'm a fan of simple powerful and flexible tools. The PR above pursues the `id generator function`, but happy to revisit or discuss the merits further. Particularly if I've missed something - or if you feel strongly about the direction.

**Comment by newtewt** [comment]
:+1:  I'm able to use the new function and the previous idTypes as well.
