### ISSUE TITLE
Declarative Config - target.appliesToType is documented as not required but crashes if not defined

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#146]
Create a target without defining appliesToType.

Observed: Crash
Expected: No Crash

**Comment by abbyad** [comment]
I would have expected it to apply to all types related to `appliesTo`. I can't think of a case right now we'd use it as such, so will update the documentation to make it required and we should guard against it as part of this issue.

**Comment by abbyad** [comment]
One possible use case is if you want to count total form submissions without listing out all the form IDs to avoid having a stale list. Not sure that it would be valuable enough use case to implement though. We can revisit if that comes up.

**Comment by kennsippell** [comment]
Personally, I don't think it should be required. It makes sense to have this empty and not require people to filter. I think we should add a null-check in the code so we don't crash

**Comment by abbyad** [comment]
Good idea. I can revert https://github.com/medic/medic-docs/commit/7e8239c1a21b589f4b37566925aa8e68e741e1a3

**Comment by newtewt** [comment]
@kennsippell looks good to me.

**Comment by abbyad** [comment]
Reverted the changes in documentation so that `appliesToType` is not required.
