### ISSUE TITLE
Declarative Config - tasks.events[n].dueDate function cannot access the reports of the contact

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#147]
```
{
  name: 'a',
  appliesIf: () => true,
  appliesTo: 'contacts',
  events: [{
    dueDate: contact => console.log(contact.reports),
  }],
}
```

Observed: contact.reports is undefined
Expected: The reports are needed in this function for many calculations.

For example, Muso has many tasks which yield followup tasks based on data in the first report with a specific set of data. Like pregnancy_family_planning discovering a pregnancy and setting in motion their pnc followup schedules.

**Comment by newtewt** [comment]
@kennsippell  another one bites the dust. I'm seeing the reports on the contact as expected.

**Comment by kennsippell** [comment]
Wahoo!
