### ISSUE TITLE
Declarative Config - Multiple tasks emitted for different events do not have a unique id

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#148]
```
{
  name: 'a',
  appliesTo: 'contact',
  appliesIf: () => true,
  events: [
    {
      id: 'a',
      dueDate: () => Utils.now(),
    },
    {
      id: 'b',
      dueDate: () => Utils.now(),
    },
  ],
}
```

Expected: Two tasks to appear for each report
Observed: One task appears

This is because the id of the emitted task is not unique and is deduplicated in webapp. The id of the event is not included in the task's id for tasks with appliesTo: 'contact'

**Comment by newtewt** [comment]
@kennsippell  I'm trying to reproduce this in the current medic-conf and web app. Using a task similar to above where the ids are different it is generating multiple tasks. Is this if both ids are the same as in

```
{
  name: 'a',
  appliesTo: 'contact',
  appliesIf: () => true,
  events: [
    {
      id: 'a',
      dueDate: () => Utils.now(),
    },
    {
      id: 'a',
      dueDate: () => Utils.now(),
    },
  ],
}
```

**Comment by kennsippell** [comment]
If the event ids are the same (as you propose in your code snippet), I would expect one task to appear (since we expect the emitted id to collide and yield a single task). So, I would expect a single emitted task for the input you provided in both the current medic-conf version and after the proposed change.

If the event ids are different (as in my code snippet), I would expect two tasks per contact in the proposed change but one task to appear with the current medic-conf. Do you seeing multiple tasks because you have multiple contacts?

**Comment by newtewt** [comment]
@kennsippell  I am now seeing the corrected change as you described. Solid fix. Feel free to merge.
