### ISSUE TITLE
Declarative Config - Emitted targets have undefined date for targets.date = 'reported' and appliesTo = 'contacts'

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#149]
```
{
  id: 'a',
  data: 'reported',
  appliesTo: 'contacts',
  appliesIf: () => true,
 ..
}
```

Expected: Emitted instance date should be the date of creation of the contact.
Observed: Emiited instance's date is undefined

**Comment by newtewt** [comment]
@kennsippell  this looks good too. I think this is the last one holding up merging #156 .

**Comment by kennsippell** [comment]
@newtewt Nice!
