### ISSUE TITLE
Declarative Config - "JsToString" function is buggy and hopefully unnecessary

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#150]
medic-conf seems to have implemented our own custom lexer/parser code for JavaScript here in https://github.com/medic/medic-conf/blob/master/src/lib/js-to-string.js. This resulted in a number of obscure scoping and closure bugs which I found very strange to diagnose.   

I think this would be very frustrating for CHT partners -- people expect JavaScript to perform in certain ways and we should not violate those expectations with custom code transformations. This also makes code harder to unit test since the code that runs is a transformed version of what can be tested. 

I don't understand the goal of this code. I suggest we remove it.

**Comment by garethbowen** [comment]
Yeah I don't understand that either...

**Comment by abbyad** [comment]
I remember an in-person discussion many months ago, but can't remember the rational -- perhaps @vimemo does?

It is likely related to the reason why the tasks.js file contains an array [`[...]`](https://github.com/medic/medic/blob/a9a53dde60ceb3d6b08196dd697db0e869be6ecc/config/standard/tasks.js) whereas targets.js has a declaration [`var targets = [...]`](https://github.com/medic/medic/blob/a9a53dde60ceb3d6b08196dd697db0e869be6ecc/config/standard/targets.js)

**Comment by newtewt** [comment]
@kennsippell  I think this one is good to go.

**Comment by newtewt** [comment]
Closing this because it has been AT'd and Merged
