### ISSUE TITLE
Declarative Config - Improved system for file-based componentization

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#151]
The declarative system requires the use of three and exactly three files in which to define all logic for a project. This restricted file componentization prevents partners from using the following coding best-practices:

### Separation of Concerns
Task-specific logic and my target-specific logic are all in the same file. Logic for my supervisor's tasks are in the same file as my CHW's targets. General, re-usable, utility functions are in the same file as domain-specific constants for my PNC followup schedule. The value of being able to separate code by subject area is extremely important for writing maintainable and reusable code.

### Following Standard Patterns
We require partners to write code matching slightly obscure custom formats. For example, `tasks.js` is a file containing only an array and `targets.js` is a file which defines a single variable. `nools-extras.js` is a utility file where everything is public and there is no information hiding.  

JavaScript systems generally follow certain well-understood, well-defined patterns. For example, `require` the files you need, and use `modules.export` to decide what data is public. 

### Testability
Code written in custom formats is hard to test. If I have a general purpose, broadly re-usable function in `nools-extras.js` how do I write unit tests for it? I can't `require('nools-extras.js') ...  If a file is transformed by a custom lexer/parser, we need a test harness to support unit testing.

### Code Re-Use
Code clarity in partner code seems to suffer from having a lack of general re-usable tools, like `underscorejs` or `moment`. To gain access to these libraries, partners require a webapp deployment. A single partner can't leverage a library without giving that library to all partners. Code re-use is a fundamental requirement for developer productivity.

## Proposed Change
Can medic-conf support general purpose JavaScript code? Can we have the input files follow standard JavaScript conventions and allow partners to `require()` the files or libraries they need. We should enforce best practices in projects through tests, static analysis, and education - rather than through a tightly constrained framework. 

It can be as easy as having medic-conf compile the project code using standard tools like browserify or webpack instead of writing our own [custom compiler](https://github.com/medic/medic-conf/blob/master/src/lib/compile-nools-rules.js) and a [custom lexer/parser](https://github.com/medic/medic-conf/blob/master/src/lib/js-to-string.js).

I am curious to understand what is motivating us to take on the added code complexity and educational burdens of a our componentization system?

**Comment by kennsippell** [comment]
We actually also have our own [proprietary system for including code from other files](https://github.com/medic/medic-conf/blob/master/src/lib/templated-js.js). Files can use `__include_inline__('file.js')` to include the content of other files instead of the standard pattern of `require('file.js')`. This is only supported in `contact-summary.templated.js` and not in either of the other files.

**Comment by dianabarsan** [comment]
Ready for AT on `109-es6`

**Comment by newtewt** [comment]
@ngaruko  might want to give this one a go too. It was in the same branch as #109  which has been merged.
