### ISSUE TITLE
Declarative Config - appliesToType is indicated as optional for fields and cards but we do require them. 

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#164]
`appliesToType` is supposed to be optional. However, leaving it out for the `fields` array will cause a crash. Leaving it out for cards will just never show a card. 
 
Given a field with the minimum required information:
```
var fields = [{
  label: 'foo',
  value: 'bar',
}];
```

Expected: This is a valid field that should appear on the contact card
Observed:  Crash

Sample config for card.
```
  {
    label: 'Test Card',
    appliesIf: true,
    fields: [
      {
        label: 'Field 1'
      }
    ]
  },
```

**Comment by njogz** [comment]
@kennsippell I have been unable to reproduce a crash by leaving out the `appliesToType` attribute on the `fields` array. Please provide steps to reproduce if possible. Leaving out the attribute leads to the card not being shown as stated but after discussing with @garethbowen I think we should update the docs to indicate the attribute as required if the card is to be shown because having cards shown regardless of type would not make sense in certain scenarios.

**Comment by kennsippell** [comment]
It does appear that the crash has been fixed.  This bug was reported ~17 months ago, and there has been significant code churn since then. I failed to identify exactly which commit/which release fixed the crash.

Why make appliesToType required? Please elaborate on the scenarios you are considering. 

A scenario I consider relevant is to "show a card for all contacts" -- standard and useful. To do that today, you'd need to list every single contact type in the `appliesToType` which can be a lot of types and adds maintenance costs to keep in sync if a new contact type are added. Thus it is my opinion, when the appliesToType is absent the card should display for all. This would seem to align with the documented behaviour which is "required: no".

**Comment by garethbowen** [comment]
The advantage of making it required is we could catch bugs and performance issues where this property was accidentally omitted. The disadvantage is obviously that it makes the system less flexible.

I'm struggling to come up with an example of a card that would make sense on a person and a place. @kennsippell Can you think of a card like that?

**Comment by kennsippell** [comment]
The date the contact was created in the system?
The type of contact you are viewing (currently the icon is only UI indication)

It's also possible to have a pattern like this where it might be inconvenient/less readable to require the appliesToType

```
if (condition) {
  cards.push(myCard);
}
```

**Comment by garethbowen** [comment]
It feels like a stretch for cards, but fields could make sense. Let's change the code for both so if it's undefined it applies to all and update the documentation to make that clear.

**Comment by garethbowen** [comment]
Ready for AT in `164-appliesToType-optional`. Documentation update: https://github.com/medic/cht-docs/pull/300

**Comment by newtewt** [comment]
@njogz  feel free to close. I've test both cards and fields with these scenarios. 

No `appliesToType` defined. Shows on contacts and places but custom and our standard types. 
Set to person
Set to custom person type
Set to custom place type
Set to standard place type
