### ISSUE TITLE
Declarative Config - Document changes which result in appliesTo=false don't cause the task to disappear

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#168]
Given this task:
```
{
    appliesTo: 'contacts',
    appliesIf: contact => contact.reports.length == 0,
    actions: [{
      form: 'myForm',
    }],
}
```

Create a new contact.
A task will appear.
Complete the task.

Expected: The task should disappear.
Observed: The task remains. If you refresh the browser, the task disappears.

**Comment by abbyad** [comment]
We have seen this sort of problem a lot, especially in the early days of Tasks. This gave rise to the [troubleshooting tip](https://github.com/medic/medic-docs/blob/master/configuration/developing-community-health-applications.md#troubleshooting):
> Tasks is not clearing: Make sure the the code that generates the task is immutable, and that the resolved condition is correct.

In your example you should always show the task, and have it resolved when the conditions are met.

```js
{
    appliesTo: 'contacts',
    resolvedIf: contact => contact.reports.length > 0,
    actions: [{
      form: 'myForm',
    }],
}
```

That said, if that could be made clearer, or not a issue, it would be good to discuss further.

**Comment by kennsippell** [comment]
Given that reports can be edited.  Looking through Muso's declarative config, there doesn't appear to be any `appliesIf` functions that rely only on "immutable" data. 

There are memory implications of using `resolvedIf`, because we store a copy of every emitted event. Moving all this logic from `appliesIf` to `resolvedIf` will cause performance to degrade. Basically causing a new object to be created and stored for every `{ task * report }`. 

Looking at the code, tasks don't clear when their dueDate expires. So given `events: [{ days: 1, start: 0, end: 0 }]`, if the dueDate comes and goes, the task will remain.

**Comment by garethbowen** [comment]
Code was added to refresh the livelists to remove tasks that were old: https://github.com/medic/medic/issues/1947

**Comment by kennsippell** [comment]
The immediate action I'm taking for this is to update the declarative config with more details of this interaction. 

For this issue, we can either 1) have me propose a solution in the declarative config code which i think would do a pretty decent job of solving this for declarative config only, 2) we can close this as won't fix/by design, or 3) we can remove this from the 3.5 release and pick it up down the road.

Looking for clarity on how to proceed.

**Comment by abbyad** [comment]
I would think option 3. It would be nice to fix at some point, but requires a relatively large amount of work while there are (in my opinion) higher priority bodies of work out there to tackle first.

**Comment by kennsippell** [comment]
> Code was added to refresh the livelists to remove tasks that were old: medic/medic#1947

@garethbowen I don't see any code which actually removes expired items. The [code in LiveList](https://github.com/medic/medic/blob/master/webapp/src/js/services/live-list.js#L543) which is run at midnight seems to refresh the description of the task, but I can't find any logic which actually removes it. Maybe I'm missing something?

I moved my calendar forward 3 years, triggered the 'at midnight' event in LiveList. This is what I saw for a task which should disappear after 24 hours:
![Screenshot from 2022-04-06 00-51-45](https://user-images.githubusercontent.com/9014751/55385542-42b4d480-54e2-11e9-8930-ad5def8985d8.png)

**Comment by garethbowen** [comment]
Maybe. I was sure there was code somewhere to remove old tasks, but clearly this is not it! It seems like a webapp issue more than a medic-conf one. I assume if you refresh the browser it disappears?

**Comment by kennsippell** [comment]
> I assume if you refresh the browser it disappears?
Yes

**Comment by garethbowen** [comment]
Ok. Let's move it to medic/medic, make it a bug, and schedule it for investigation in 3.6.0. What do you think?

**Comment by kennsippell** [comment]
https://github.com/medic/medic/issues/5564

**Comment by kennsippell** [comment]
The original bug reported here should now be ready for AT on webapp branch `tasks-v2`. If the `appliesIf` function ever returns false, tasks will now disappear. The difference should be that they move  to state Cancelled instead of state Completed which is set if they are "resolved".

**Comment by ngaruko** [comment]
LGTM
![image](https://user-images.githubusercontent.com/6979995/70871165-1a81ed00-2001-11ea-846f-5ad4144c3e2b.png)
