### ISSUE TITLE
Add a command to update the parents of contacts

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-conf#172]
Frequently tech leads have to move people or places to be in a different part of the hierarchy. This is very complicated because we store the entire hierarchy inline in child contacts and reports so it can be a cascading operation which can easily lead to data corruption. As such it should be a fully supported and tested feature.

- Investigate how this is being done currently as a basis for this script.
- Add a dry run flag or prompt for user confirmation once you've found out how many docs are going to be updated. It might make sense to write the docs to disk, allowing the user to check them, before uploading them all to the server. This warning should include the impact particularly on users who will have to replicate the new docs.
- This will need to be resumable if it's interrupted half way through so data isn't left orphaned/corrupted. For example, if the docs are written to disk, they can be deleted once successfully uploaded, so the resumption is to continue uploading any files that are left (hint: use the [upload-docs function](https://github.com/medic/medic-conf/blob/master/src/fn/upload-docs.js)).
- Since 2.13.0 we've [minified the hierarchy](https://github.com/medic/medic/issues/2635) to reduce duplication. If that's supported in the instance being used be sure to minify any doc being upgraded (hint: use the [lineage shared lib](https://github.com/medic/medic/blob/master/shared-libs/lineage/src/lineage.js#L430)).

**Comment by kennsippell** [comment]
If anybody has thoughts on these questions:

* Should this support all version of the webapp? 
* Would you expect that this script needs to behave differently for any specific versions of the app?
* As one example of the above problem. @garethbowen Does flexible heirarchy have any impact on this?

**Comment by garethbowen** [comment]
@kennsippell In 2.13.0 we made a major change to [stop embedding the entire parent object in the child doc](#2635). I think we're ok only supporting pre 2.13.0+ projects, but it may be worth documenting somewhere in case someone tries... That means the script should ensure the parents are minified when it's done. I can't think of any other changes in this area that you'd have to support.

The only challenge with the upcoming configurable hierarchy is with regards to validation. I don't think we should allow people to script moving a clinic to have a person as a parent (for example). When working on the script check for `settings.contact_types` ([documentation](https://github.com/medic/medic-docs/pull/99/files#diff-1083f7afb918dcdc17e4528c840867e1R172)) - if it exists use that to validate the new relationship, otherwise fall back to the hardcoded relationships, ie: `district_hospital` begets `health_center` begets `clinic`, and `person` can have any parent.

**Comment by nomulex** [comment]
To me, the feature description is for a bulk operation(move many contacts) is there consideration for a granular operation (move one contact). I think this is what most partners need on a day to day .  by copy to disk what are we looking at here ? the server disk or the client disk ?  we may face connectivity challenges if we are uploading many docs.

**Comment by garethbowen** [comment]
We should definitely support moving a single contact, as well as being able to scale upwards to moving lots of contacts.

I was thinking the docs could be written to the local disk before uploading. Other functions in medic-conf do this too which gives the user a chance to preview the changes that will be made before committing. It also means that the upload step is simply picking the next batch of docs from disk and uploading them. If that succeeds then the docs can be deleted from the local disk, but if it fails we can easily try again until it succeeds. To work around some of the connectivity issues medic-conf can be run in the cloud, which means the script will continue even if your connection goes down.

Alternatively, we could provide an API for moving people/places which means all the fetching and updating would be done on in the cloud.

**Comment by kennsippell** [comment]
> This warning should include the impact particularly on users who will have to replicate the new docs.

Can handle the situation where users have to sync more documents. But what about users who are having docs "removed" from their view?

Consider this scenario:
- Given `clinic_1` which is a child of `health_center_1` which is a child of `district_1`.
- Given an offline user with `facility_id=health_center_1`
- I login as this offline user, and I can view `health_center_1`.
- Run this proposed script to move `clinic_1` to be a child of `health_center_1`

This should effectively remove the documents from the user's view. But these documents will not be removed, now will the user receive errors or warnings when editing these documents. Should we similarly notify the list of users who will have documents removed? Should we recommend these users to clear cache and re-sync?

**Comment by garethbowen** [comment]
> Should we similarly notify the medic-conf operator a list of users who will have documents removed? Should we recommend these users to clear cache and re-sync or something similar?

Yes, we should do _something_ here. I'm not sure what the right thing is but if you can easily work out the affected users and show it to the configurer that would be a great start.

> Should we consider having this scenario not "fail silently" in future versions of the app?

Yes, definitely. I thought there was an issue about this but I can't find it. Ideally we'd do some kind of doc purge to remove the docs from users who are no longer allowed to see them. This would also affect when the user's contact is changed, or the replication depth is reconfigured, etc. This is definitely a separate issue.

**Comment by kennsippell** [comment]
> Yes, we should do something here. I'm not sure what the right thing is but if you can easily work out the affected users and show it to the configurer that would be a great start.
#197 

> I thought there was an issue about this but I can't find it.
medic/medic/issues/5701

**Comment by ngaruko** [comment]
Confirmed with @mukesh2006 - Will merge and close
