### ISSUE TITLE
Medic-conf does not backup, upload, or convert forms by default

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#185]
Scenario:
Navigate to `~/webapp/config/standard` and run `medic-conf`

Expected: Extracts all forms in the `forms/app` folder
Observed: No forms are converted
```
INFO convert-app-forms complete. 
INFO Starting action: convert-collect-forms… 
```
Regression from https://github.com/medic/medic-conf/commit/95222da67d7b154cfeb48f8c7099fd8451bb85fe

**Comment by newtewt** [comment]
@kennsippell there are a few PRs related. Should this be done against 2.0.4 or a specific branch?

**Comment by newtewt** [comment]
I believe I've covered majority of the functionality for the actions and they seem to be working still. The default action is also working. Closing this one.
