### ISSUE TITLE
Validate app_settings schema before compilation

### ISSUE THREAD

**Issue by eljhkrr** [medic/medic-conf#192]
Medic-conf should be able to validate the schema applied in app_settings.json before uploading it
to an instance. This will smoothen the deployment process by calling out invalid declarations and avoiding unexpected behavior. Proposed specification can be found [here.](https://json-schema.org/specification.html)

**Comment by garethbowen** [comment]
Definitely a good idea! I think this is a duplicate of https://github.com/medic/medic/issues/4783

**Comment by eljhkrr** [comment]
Yeah, I reviewed that ticket and opted to raise this one to track development of this on the conf side. I was also wondering if we got this working in medic-conf, would it be still be necessary to validate settings again in the API. I know there are changes between the input file and what is uploaded, but I'm of the opinion that unit tests are more appropriate for the compilation stage.

**Comment by eljhkrr** [comment]
Ahh, I misunderstood Stefan's approach which would work better in a world with version differences. Closing in favor of https://github.com/medic/medic/issues/4783
