### ISSUE TITLE
Support creating custom locales based on app version

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-conf#199]
[We changed the translation docs structure in 3.4](https://github.com/medic/medic/issues/3128). 

We also updated medic-conf to use the new translations structure (https://github.com/medic/medic-conf/blob/master/src/fn/upload-custom-translations.js#L47), but that doesn't cover the creation of new locales, which would always be created using the old structure. 

The structure of new locales should depend on the version of the app the translations will be uploaded to.

**Comment by dianabarsan** [comment]
Ready for AT on `5617-correct-custom-translations`.

For AT, try to upload a custom locale to any app version (at least target 3.5, 3.4, 3.3 and 2.x) and make sure that your new translations have the correct structure.

**Comment by newtewt** [comment]
I was able to upload custom translations to 3.2.1, 3.4, 3.5, and 2.18.0 and assign them to the admin user and see them displayed. Aside from the bug in 3.4 with loading contacts I think this change is good to go. I'm not sure which PR this is associated to @dianabarsan  could you merge or give me the PR?

**Comment by dianabarsan** [comment]
I linked the PR to the issue. Sorry.

**Comment by newtewt** [comment]
Thanks, closing it out.
