### ISSUE TITLE
When uploading custom translations we should indicate better that the admin needs to give the language a name. 

### ISSUE THREAD

**Issue by newtewt** [medic/medic-conf#200]
Currently when uploading custom translations the user doesn't get a message or prompt or any notification that the name of their translation is going to be `TODO: please ask admin to set this in settings UI`. We should at the very minimum warn in the upload that they need to go in and name the language. Would be nice if we could prompt or create a standard somewhere to set a value and it gets named automatically.

**Comment by garethbowen** [comment]
Let's simply error out if the name isn't provided.

**Comment by kennsippell** [comment]
This is ready for AT in `eljhkrr:200_language_name`.

I'd like to bring this issue into the 3.7 release as a solution for [this](https://github.com/medic/medic/pull/5945#issuecomment-534006085) problem which I am having making the CHT-Reference-App the default configuration. There are other ways to fix this - but it is my opinion this PR is the cleanest path forward.

**Comment by newtewt** [comment]
This works as expected, valid language codes are being translated automatically where invalid/unknown are showing a warning and setting to the default.
