### ISSUE TITLE
Make app_settings more modular

### ISSUE THREAD

**Issue by heikohornung** [medic/medic-conf#214]
**Is your feature request related to a problem? Please describe.**
`app_settings.json` contains parts that can be configured/edited manually and other parts that are inserted by `medic-conf`. If one contributor works in a branch on the manual part and another on e.g. tasks or targets, app_settings can create merge conflicts that are tedious to review.

**Describe the solution you'd like**
If the editable part of `app_settings.json` was moved to a separate file, and `medic-conf` completely generated `app_settings.json`, it could be put into .gitignore and would not cause merge conflicts.

**Describe alternatives you've considered**
An alternative is to have more coordination among contributors, but that's less efficient/safe that separating things.

**Additional context**
If one wanted to take the idea of modularization one step further, one could even think of `*.d` directories for configuration files like in linux, e.g. a `tasks.d` directory where one could create one file per task and/or form.

**Comment by kennsippell** [comment]
We might consider having the "tasks.rules" and "contact summary" scripts attached to the ddoc instead of being included as attributes. These attributes can become quite large (especially if they require third party libs), and we _frequently_ load/dispose the settings document in memory in the webapp.

**Comment by kennsippell** [comment]
Also see https://github.com/medic/medic-conf/issues/68

**Comment by derickl** [comment]
@njogz Thank you for the quick walkthrough of the ongoing implementation!

A complimentary enhancement to this issue would be having environment-specific subsets of app_settings.

base_settings would be the main file and probably a base_settings.prod and a base_settings.dev. Could we hide this behind environment flags?

The reasoning behind this is that we realistically have different settings per environment. This usually applies to outbound and gateway settings.

cc @kennsippell

**Comment by njogz** [comment]
@derickl Thank you for the feedback. As the implementation for your suggestion can be independent of the modularisation could you please create a new issue for the environment flags?

**Comment by dianabarsan** [comment]
Ready for AT on `214-modular-app_settings-file`.

**Comment by newtewt** [comment]
@njogz  could you provide a summary of what changed here? The readme only mentions `base_settings.json, forms.json, and schedules.json`. It seems like more of our app_settings could be pulled out into their own files.

**Comment by njogz** [comment]
@newtewt more app_settings can indeed be pulled into their own files. I didn't get any feedback on which sections of the app_settings should be pulled out into their own files from tech leads so decided to start with `schedules` and `forms` as requested in #68 

Summary of changes:

- basic configuration moved to the `base_settings.json` file so the `app_settings.json` is generated and can be git ignored
- `schedules` and `forms` settings pulled into individual files
- Added a warning if `schedules` or `forms` is defined in a separate file and in `base_settings.json`
- Added validation for `schedules.json` and `forms.json` files
- `initialise-project-layout` command initialises the project with the new `base_settings.json`, `schedules.json`,  and `forms.json` files

**Comment by newtewt** [comment]
Thanks @njogz  I'll start working on this. We should probably update https://docs.communityhealthtoolkit.org/apps/reference/app-settings/ to be clear that the app_settings.json is now more of a generated file and shouldn't be edited.

**Comment by newtewt** [comment]
I think forms.json should go in the forms folder. What are your thoughts @njogz

**Comment by njogz** [comment]
Good suggestion but I think it would be a bit confusing if all other settings files were in the `app_settings` folder but forms.json was the only one in a different folder.

**Comment by newtewt** [comment]
@njogz  I made a comment on the PR about adding a full path for the JSON files and we need a cht-docs update. Other than that I think this is ready to go. 

Validated app_settings.json still works by it's own(backwards compat) and warns of new changes. 
Validated the warnings when base_settings and the JSON files exist.
The JSON files take precedence over what's defined in base_settings but you are warned. 
JSON parse warnings in the files. 
New init project works properly.
