### ISSUE TITLE
Url command-line options are required even for actions which don't use it (regression)

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#218]
In medic-conf v1, this command would work without error: `medic-conf compile-app-settings`

In medic-conf v3, the same command displays error: `ERROR Missing one of these required parameter: --local --instance --url`

For this action (and some others), the url information isn't actually required and so the command-line should also not be required.

**Comment by SCdF** [comment]
Fixed in #253

**Comment by SCdF** [comment]
Code is ready to AT on `218_refactoring`.

I'm not sure how we do AT on `medic-conf`, but if you check out the branch, do an `npm ci` and then run `node ./src/bin/medic-conf.js` it should suffice?

AT:
 - Any command or combination of commands that you think shouldn't need to know about a CHT instance to function should work fine without passing `--local`, `--url` etc
 - Any command or combiantion of commands that you think does need to know about a CHT instance to function should require that you pass `--local`, `--url` etc

**Comment by michaelkohn** [comment]
I think this issue (218) and/or #253  will address the issue I saw in [#154](https://github.com/medic/medic-docs/issues/154).  

But... I also think that we should update the [documentation for medic-conf](https://github.com/medic/medic-conf)  per @SCdF 's AT comments:

> - Any command or combination of commands that you think shouldn't need to know about a CHT instance to function should work fine without passing --local, --url etc
> - Any command or combiantion of commands that you think does need to know about a CHT instance to function should require that you pass --local, --url etc

**Comment by ngaruko** [comment]
LGTM
**with medic-conf _master**_
![image](https://user-images.githubusercontent.com/6979995/68812918-1d738000-06d9-11ea-8719-f693928fd35f.png)


**_and on branch_**
![image](https://user-images.githubusercontent.com/6979995/68813023-6a575680-06d9-11ea-900e-74e74d99f91d.png)

**Comment by ngaruko** [comment]
@SCdF There are conflicts on the [branch](https://github.com/medic/medic-conf/pull/265). Can you please fix those before we merge and close the issue? Thanks..

**Comment by SCdF** [comment]
The conflict was minor so doesn't require re-AT. Merged to master. A new release of medic-conf is in preparation.
