### ISSUE TITLE
Actions that write files seems to be broken create-users, fetch files.

### ISSUE THREAD

**Issue by newtewt** [medic/medic-conf#221]
Csv to docs should create a users.csv file in the directory you're running in when a csv call users.csv exists in a csv directory.  What happens now is the users.csv is created in the directory but it is empty.  

Using [seed data json](https://drive.google.com/drive/u/1/folders/1At2nQR-OAjpUVoEyrE0ekrHP-sNLeYhc)

run fetch-csvs-from-google-drive
run csv-to-docs

once completed the users.csv exists but is empty.

**Comment by newtewt** [comment]
Another example of this is fetching files form google. Everything seems to run but never actually writes the csvs to disk.

**Comment by kennsippell** [comment]
@newtewt I'm having a hard time determining how impactful this bug is on your your QA workflows. Is this blocking any testing or alike? Do you need a quick fix for this?

**Comment by newtewt** [comment]
@kennsippell it's more of an inconvenience than a blocker.

**Comment by garethbowen** [comment]
Ready for AT in `221-write-files-seems-broken`

**Comment by garethbowen** [comment]
Apparently this is urgent so scheduling for 3.7.0.

**Comment by newtewt** [comment]
Cool! I'm able to fetch files and create users csv again.
