### ISSUE TITLE
Unit tests fail when run locally

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#236]
To repro: npm test
Expected: Tests pass
Observed: Tests pass in travis but fail locally

We should avoid our need to copy test collateral around and string things together with a custom working directory. We can improve the simplicity of our tests by mocking interactions to the file system.

**Comment by garethbowen** [comment]
@kennsippell I got mine to pass by installing the supported version of pyxform, ie:

```sh
sudo pip uninstall pyxform-medic
sudo python -m pip install git+https://github.com/medic/pyxform.git@medic-conf-1.17#egg=pyxform-medic
```

Can you check if this resolves your issue too?

I think the copying of files is by design so these are integration tests rather than unit tests. There has been plenty of debate within the team about which is more useful. So long as these tests are fast and reliable (which these are for me now that they're passing) I'm comfortable with using integration tests in this way. If they become slow and/or unreliable we could think about having unit tests as well as integration tests much like we do in medic/medic.

**Comment by kennsippell** [comment]
Yes, all tests are now passing locally for me. I would consider this issue resolved, but maybe we could improve things by having the tests abort with a clear error if the dependency isn't installed?

Regarding the testing pattern used here, "fast and reliable" is a great start. But tests that require an external script to copy files or change the working directory also require custom setup to run in a debugger. 
Tests become unnecessarily hard to read and understand when they load data from external files (even more unnecessary for empty files, or single-line files which we use often in these tests). 
It is harder to maintain and author tests that require 5 files with one line each, compared with five lines mocking this content in a single test file. Personally, I feel that file management reduces my willingness to add edge-case tests.
Mocking interactions with the file system does not prevent us from writing effective integration tests which target interactions between specific modules. 

medic-conf v3.0.5 now supports the `--source` parameter to pull configuration files from specific directories. Even if we continue to write tests that use the file system, one improvement we might consider is to use that mechanism to avoid needing to change the working directory. Then tests can readily run in a debugger without custom setup.

Feel free to close this issue or move it to backlog if you don't feel these suggestions are worth prioritising in 3.8.

**Comment by garethbowen** [comment]
> I would consider this issue resolved, but maybe we could improve things by having the tests abort with a clear error if the dependency isn't installed?

The problem for me wasn't that I didn't have it installed I just had the wrong version. I'm not sure how to check this.

> Mocking interactions with the file system does not prevent us from writing effective integration tests which target interactions between specific modules.

It does, however, stop us testing integration between our code and the `fs` library. The great thing about the integration tests is they'll break we're using the API wrong, or the API is broken on a later version of Node.

> Feel free to close this issue or move it to backlog if you don't feel these suggestions are worth prioritising in 3.8.

I think there is great value in the integration test suite we have, though it's a bit of a pain to run locally every commit. My suggestion is the next time we make any future change to medic-conf we should isolate the integration test suite and add a unit test suite. This will slow down the development of the next feature but once the suite is up and running we can expand it with every change eventually reaching acceptable coverage.

Proper testing is a requirement of all PRs so I don't think we need to create a new issue just for this. Let's both of us resolve to be more strict in upcoming PRs to ensure we start to develop the test suites so we end up with the confidence of full integration testing as well as the convenience of a reliable unit test suite.
