### ISSUE TITLE
convert-*-forms actions silently convert nothing when extraArgs are provided

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#240]
To Reproduce: `medic-conf --local compile-app-settings convert-app-forms upload-app-forms -- --debug`

Expected: 
The `compile-app-settings` action should compile in `--debug` mode
The `convert-app-forms` action should convert all app forms

Observed:
No app forms are converted

**Comment by garethbowen** [comment]
Ready for AT in `240-form-filters`

**Comment by abbyad** [comment]
**Seemingly related issue**: Using medic-conf 3.0.6 I can convert a single form, but uploading always uploads all forms.

For example:

### convert-app-forms

```
>medic-conf --url=${url} convert-app-forms -- pregnancy
INFO Processing config in default.
INFO Actions:
     - convert-app-forms
INFO Starting action: convert-app-forms…
INFO Converting form ${path}/forms/app/pregnancy.xlsx …
Conversion complete!
INFO convert-app-forms complete.
```

### upload-app-forms

```
>medic-conf --url=${url} upload-app-forms -- pregnancy
INFO Processing config in default.
INFO Actions:
     - upload-app-forms
INFO Starting action: upload-app-forms…
INFO Preparing form for upload: death_report.xml…
[...]
```

**Comment by kennsippell** [comment]
I've updated the PR above to use the same filtering logic in both `convert-forms` and `upload-forms`.

**Comment by garethbowen** [comment]
Ready for AT again.

**Comment by ngaruko** [comment]
**_Before_**
![image](https://user-images.githubusercontent.com/6979995/67178521-94499000-f42f-11e9-8ed0-e42b15fbdba3.png)
 **_After /on branch_**
![image](https://user-images.githubusercontent.com/6979995/67178883-dd4e1400-f430-11e9-849c-e5bb47cc6c08.png)
