### ISSUE TITLE
Add validation to the upload custom translations function

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-conf#254]
In https://github.com/medic/medic/issues/5863 we discovered that some projects have translations that use messageformat that fail to parse and throw errors every time they're called. It can be quite challenging to get the format correct, and if you get it wrong the errors are swallowed so unless you check carefully it's easy to miss.

We should run validation on upload to ensure all translations are valid. You can use the [messageformat library](https://www.npmjs.com/package/messageformat) to test compiling the translation.

The [POE export script](https://github.com/medic/medic/tree/master/scripts/poe) also runs a different set of validations on the default translations to ensure they're correct. Include those validations here too, and conversely, add the messageformat validation check to that script.

Consider having warnings (eg: missing translations) which can be ignored, as well as errors (eg: messageformat doesn't compile) which can't be ignored.

**Comment by mrsarm** [comment]
@garethbowen could you point out an example ? I couldn't find any example of a translation using "messageformat" syntax, and I need to find one to be sure I understand well the problem and I can test it locally.

I checked out [config/default/translations/messages-en.properties](https://github.com/medic/cht-core/blob/master/config/default/translations/messages-en.properties) and [config/standard/translations/messages-en.properties](https://github.com/medic/cht-core/blob/master/config/standard/translations/messages-en.properties), and I did check other config repos at https://github.com/medic but with no success. Does medic-conf export translations with "messageformat" syntax al all? if yes, and supposing transalations are used in XForms, how the variables needed to pass to messageformat are defined?

**Comment by garethbowen** [comment]
@mrsarm We define translations in two place. The config ones you found should only contain translations for the configured parts of the app (forms, tasks, etc). We also have base translations which are for all the non-configurable parts of the app (menus, tabs, etc) which has some messageformat syntax values such as [contacts.visits.visits](https://github.com/medic/cht-core/blob/master/ddocs/medic/_attachments/translations/messages-en.properties#L553).

medic-conf doesn't use the translations at all but it does upload them all to the project. A project could decide to change the default translation of `contacts.visits.visits` to be "{VISITS, plural, one{encounter} other{encounters}}" to fit their preferred terminology. If they do that and don't fully understand messageformat they could easily make a mistake and break the syntax. If that happens right now medic-conf will blindly update the translations and it'll break silently in the UI.

**Comment by mrsarm** [comment]
@garethbowen ,

Here are the new PRs related with this ticket:

- The new module **"translation-checker"** where I moved all the code that perform the validations: https://github.com/medic/translation-checker/pull/1 (and I closed [this one](https://github.com/medic/medic-conf/pull/349) with the original code)
- This new [pr](https://github.com/medic/medic-conf/pull/356) for this project that uses the new module above.
- Same module applied to the **poe script** to perform the same validations when translations are imported from poeditor.com: https://github.com/medic/cht-core/pull/6597

**TODO**:
- There is a possibility of "false errors" when a translation has long HTML code, like [here](https://github.com/medic/config-itech/blob/master/zazic/translations/messages-en.properties#L369), so I'll add a new argument `--skip-translations-check` to skip the checks if you agree.

**Notes**:

- Until the first PR is not merged and published in the npmjs.org registry as a public NodeJS module, we cannot merge the other two.
- I the PR mentioned above from cht-core there are some translations corrections that were found using the new version of medic-conf, and also many errors found in the translations from poeeditor.com that I already fixed from the site, using also the new poe script from the PR above.
- I also found some errors in the config-covid repo using the new checks: https://github.com/medic/config-covid/pull/107

**Comment by garethbowen** [comment]
> There is a possibility of "false errors" when a translation has long HTML code

Why does this output an error? Can't we fix it so it doesn't return an error? If it throws an error in our code will it also throw an error when it gets to the webapp?

**Comment by garethbowen** [comment]
> There is another case that looks very exceptional and at the beginning I thought it was related with Messageformat failing to compile because HTML tags in the message but it wasn't the case: here is a long HTML that has this string inside "title:{Aida TO Carmen}", where brackets { } are used but is not a placeholder nor a Messageformat, so there is no easy way to discard cases like these without making complex regex evaluations that may cause to dismiss bad Messageformat or placeholders usage. In fact I have tested several config repos and I only find that example.
Anyway, I added the --skip-translation-check flag in medic-conf to skip translations check when a case like this is unavoidable, although in the case mentioned the brackets may be replaced by HTML number codes: title:&#123;Aida TO Carmen&#124;.

I think that specific translation is no longer used, but thinking about the generic case, my concern is that if someone does have translations that break the regex then they will always use `--skip-translation-check` and then none of their other translations will be checked either. I think a nicer solution would be to allow users to add a file listing keys to ignore so they can opt out of checks for only that key and still benefit from checking all the other keys. I think what you have is fine for now. Please raise a new issue in medic-conf to add this feature and we can do it in the next round.

All the PRs are now approved. I think you now just need to get the builds all passing then it'll be ready for AT.

**Comment by mrsarm** [comment]
Moved to **Ready for AT**.

> I think a nicer solution would be to allow users to add a file listing keys to ignore so they can opt out of checks for only that key and still benefit from checking all the other keys

@garethbowen I'll create the ticket and leave it in draft state until this ticket is merged so it makes sense.

#### Summary of what is done for test

There are 3 PRs, one is a dependency for the others two:

- medic/translation-checker#1 : the new module **"translation-cheker"**, base for the other PRs, already published in Npmjs: https://www.npmjs.com/package/@medic/translation-checker , otherwise it would be impossible to build in CI the other two PRs. Because it is just a library repo, there is nothing to test manually from this repo (other than run the automated tests).
- https://github.com/medic/medic-conf/pull/356 : **medic-conf** changes, take a look at the PR description to see what are the changes about.
- [poe PR](https://github.com/medic/cht-core/pull/6597): changes in the **"poe" script** in the cht-core scripts. There is also a introduction about the changes in the PR description, and dependencies were updated due critical vulnerabilities found.

**Comment by ngaruko** [comment]
Tested for the following conditions :

1. Empty message found for key:
`WARN Empty message found for key 'report.delivery.pnc_visits.who_note' in 'en' translation `

1. No `translations` directory:
`WARN Could not find custom translations dir: /Users/bede/Medic/medic-dev/cht-core/config/default/translations `

1. Wrong filename
`ERROR The following file/s have wrong ISO 639 language code: messages-en copy.properties `

1. Missed placeholder
`ERROR Cannot compile 'sw' translation with key 'schedule.child_health' has placeholders, but base translations does not have placeholders `

1. Wrong placeholder: (modify an existing {{placeholder}})
```
ERROR Cannot compile 'id' translation with key 'messages.schedule.postnatal.day_0_overdue' has placeholders that do not match any in the base translation provided 
ERROR Found 1 errors trying to compile translations
You can use messages-ex.properties to add placeholders missing from the reference context. 
```

**Comment by ngaruko** [comment]
...and changing translations in `poe` and running [`./cli.js export .`](https://github.com/medic/cht-core/tree/master/scripts/poe#poe-cli)
```
  ◡ Exporting translations...	id saved to /Users/bede/Medic/medic-dev/cht-core/scripts/poe/./messages-id.properties
  ◠ Exporting translations...Error: Cannot compile 'fr' translation messages.c.validation.weeks_since_birth = 'Le format pour  enregistrer {patient_id}} est incorrect, merci de vous assurer que l'âge (semaines) est compris entre 0 et 90.' : Expected "#", "{", doubled apostrophe, end of input, escaped string, or plain char but "}" found.
Error: Cannot compile 'fr' translation reports.none.n.months = '{MONTHS, plural, un{Aucun rapport durant ce mois.} autre{Aucun rapport dans les # mois passés.}}' : Invalid key `un` for argument `MONTHS`. Valid plural keys for this locale are `one`, `other`, and explicit keys like `=0`.
Error: Cannot compile 'fr' translation tasks.none.n.weeks = '{WEEKS, plural, un{Aucune tache pour la semaine prochaine.} autres{Aucune tache dans les prochaines # semaines.}}' : Invalid key `un` for argument `WEEKS`. Valid plural keys for this locale are `one`, `other`, and explicit keys like `=0`.
Info: Found 6168 empty translations trying to compile
Error: Found 3 errors trying to compile
Error: Invalid placeholders or "messageformat" messages!
    at download (/Users/bede/Medic/medic-dev/cht-core/scripts/poe/lib/poe.js:66:13)
```
Good to go @mrsarm 👍

**Comment by mrsarm** [comment]
Merged pending PRs into master.
