### ISSUE TITLE
Exclamation marks are double escaped in upload-custom-translations

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-conf#259]
The translation files we export from POE and ship as default contain escaped exclamation marks, for example:

```
instance.upgrade.confirm.warning.text = This action cannot be undone, make sure your data has been backed up\!
```

On first run these are inserted into the database with _id `messages-en` and correctly unescaped, for example:

```
"instance.upgrade.confirm.warning.text": "This action cannot be undone, make sure your data has been backed up!",
```

If the files are uploaded through the admin UI the files are unescaped correctly.

However when I use `upload-custom-translations` the exclamation marks are double escaped and the backslash is rendered in the UI, for example:

```
"instance.upgrade.confirm.warning.text": "This action cannot be undone, make sure your data has been backed up\\!",
```

### Reproduction

1. Navigate to `cht-core/ddocs/medic/_attachments`
2. Execute `medic-conf --local upload-custom-translations` replacing `--local` with the test instance as required.
3. Go to App Settings > Upgrade Instance
4. Pick a version and click "Upgrade" and wait for the dialog - don't submit the dialog!
5. Notice the dialog message is: "This action cannot be undone, make sure your data has been backed up\!" (NB: the backslash just before the exclamation mark).

### Expected

The message should be "This action cannot be undone, make sure your data has been backed up!"

Original noticed in medic/cht-core#5392

**Comment by garethbowen** [comment]
Ready for AT in `259-exclamation-mark-double-escaped`

**Comment by ngaruko** [comment]
LGTM
**before**
![image](https://user-images.githubusercontent.com/6979995/68805932-a84c7e80-06c9-11ea-80d7-a19130d99926.png)

 **Using `medic-conf` branch (local):**
![image](https://user-images.githubusercontent.com/6979995/68808113-f5caea80-06cd-11ea-9dff-c01e3a9d8607.png)
