### ISSUE TITLE
Add configurable hierarchy support to doc references in csv-to-docs

### ISSUE THREAD

**Issue by abbyad** [medic/medic-conf#273]
We should add support for referencing or including docs of any type of place, as now possible as of 3.7 of cht-core with configurable hierarchies.

With configurable hierarchy it looks as though referecing another doc with csv-to-docs only works with the original place types (`clinic`, `health_center`,`district_hospital`)
https://github.com/medic/medic-conf/blob/4afeef429b7987f514c594a4936092a6e956cd6b/src/fn/csv-to-docs.js#L13
https://github.com/medic/medic-conf/blob/4afeef429b7987f514c594a4936092a6e956cd6b/src/fn/csv-to-docs.js#L85-L87

There already appears to be support for creating places with configurable types:
https://github.com/medic/medic-conf/blob/4afeef429b7987f514c594a4936092a6e956cd6b/src/fn/csv-to-docs.js#L101)

**Comment by garethbowen** [comment]
The workaround for this is to use the the `"contact"` type in the query, which matches any type, eg: `contact:_id OF contact WHERE external_id=COL_VAL`.

**Comment by dianabarsan** [comment]
Ready for AT on `273-csv-to-docs-configurable-hierarchy`

**Comment by ngaruko** [comment]
LGTM
Tested by running `medic-conf`[ local install](https://github.com/medic/medic-conf#testing-locally).
**Master**
![image](https://user-images.githubusercontent.com/6979995/85972363-e6fa3380-ba23-11ea-869f-c6ce033a2a91.png)

**_Branch_**
![image](https://user-images.githubusercontent.com/6979995/85972399-05602f00-ba24-11ea-9799-082c13cd11d1.png)

**Comment by garethbowen** [comment]
Merged.
