### ISSUE TITLE
Declarative Configuration - Make task/target identification attributes required data integrity of task documents

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#276]
One key impact from the tasks/target improvements in core v3.8.0, is the ability to write impact queries to understand how tasks are behaving on users phones. In current versions of the declarative configuraiton, we default to using the "index" of a task, target, or event. This is going to be problematic, because it will lead to data integrity issues if elements are ever reorderd or removed from within the configuration.

We need to enforce the following schema rules:

* Task.name is now a required unique attribute
* Task.event[n].id is now a required unique attribute when there is more than one event
* Target.id although always required, is now a required unique attribute

**Comment by kennsippell** [comment]
Ready for AT on `schema-validation`.

**Comment by dianabarsan** [comment]
Assigning myself for AT.

**Comment by dianabarsan** [comment]
LGTM.

All examples below are results of running `medic-conf compile-app-settings`.
The command fails when there is at least one schema validation error.

- Having a duplicate task name:
```
ERROR tasks.js invalid schema:
ERROR tasks.js[1] contains duplicate value for the "name" field: "one"
```

- Missing task.event[n].id when there is more than one event
```
ERROR tasks.js invalid schema:
ERROR "[1].events[0].id" is required
```

- Having a duplicate task.event[n].id (2 events use id: 'my-event-id')
```
ERROR tasks.js invalid schema:
ERROR tasks.js[1].events[1] contains duplicate value for the "id" field: "my-event-id"
```

- Missing target.id
```
ERROR targets.js invalid schema:
ERROR "[0].id" is required
```

- Duplicate target.id (2 targets use id: 'target1')
```
ERROR targets.js invalid schema:
ERROR targets.js[1] contains duplicate value for the "id" field: "target1"
```

Additionally, every task and target field has been defined, given an allowed type and marked as required/optional.
The defined schema matches the documentation available here https://github.com/medic/medic-docs/blob/master/configuration/developing-community-health-applications.md
