### ISSUE TITLE
Declarative Config - Rename passGroupWithCount to passesIfGroupCount

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#283]
Based on UAT and feedback during documentation review (medic/medic-docs#164), we should rename `passGroupWithCount` to `passesIfGroupCount`. 

It is nice to do this before medic-conf 3.1 releases so the initial release of this feature has the correct nomenclature.

**Comment by kennsippell** [comment]
@senseibara I've deployed these changes to https://sih-muso-mali.dev.medicmobile.org. Would you mind giving this another quick acceptance test?

**Comment by senseibara** [comment]
looks good to me
