### ISSUE TITLE
Hierarchy error prevents "move-contacts" action from working with parents using contact_type

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#286]
Steps: 

1. Using the default hierarchy, create a district_hospital contact.
1. Enable configurable hierarchy with a new contact type. District_hospital has this new type as a valid parent. (https://github.com/medic/medic-projects/pull/7182)
1. Create a contact of this new root-level type
1. `medic-conf --local move-contacts upload-docs -- --contacts=district_id --parent=top_id`

Expected: Moves the contact, this is valid
Observed: `ERROR Error: Hierarchy Constraints: contacts of type 'district_hospital' cannot have parent of type 'contact'`

Context:
This is blocking a hierarchy re-configurations for the `cdc-ebs` project with deadline this week.
Running webapp 3.7.1

**Comment by kennsippell** [comment]
Ready for AT on `286-move-contacts-flexible`

**Comment by PhilipNgari** [comment]
would we say this is now sorted @jonathanbataire . Any progress to share on this.

**Comment by jonathanbataire** [comment]
> would we say this is now sorted @jonathanbataire . Any progress to share on this.

Yep using @kennsippell medic-conf PR everything should work just fine
