### ISSUE TITLE
Tests fail locally when Bash completion is not setup

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-conf#290]
When running tests locally, without following the `Bash completion` step (https://github.com/medic/medic-conf#bash-completion), the suite will fail with the following error:

```
269 passing (9s)
  1 failing

  1) compile-app-settings
       should handle simple config:

      Uncaught AssertionError: expected '\n' to equal 'compile-app-settings compress-images compress-pngs compress-svgs\n'
      + expected - actual

      -
      +compile-app-settings compress-images compress-pngs compress-svgs
      
      at /home/diana/projects/medic-conf/test/bin/shell-completion.spec.js:25:14
      at ChildProcess.exithandler (child_process.js:286:7)
      at maybeClose (internal/child_process.js:1021:16)
      at Socket.<anonymous> (internal/child_process.js:430:11)
      at Pipe.<anonymous> (net.js:664:12)
```

The test reported as failed is run after `shell-completion` but the stack actually shows where the error is thrown. The problem is that the `shell-completion` test is asynchronous, but doesn't wait for the command execution: https://github.com/medic/medic-conf/blob/master/test/bin/shell-completion.spec.js#L23 and another test gets reported as failed. 

On Travis, this command runs before running tests: 
https://github.com/medic/medic-conf/blob/master/.travis.yml#L13

The test should, at least, be fixed to wait for the async command to execute.

**Comment by garethbowen** [comment]
@billwambua I've decided just to remove the test for now. If you find a solution to get this test to pass locally then we can add it back!
