### ISSUE TITLE
Add command to bulk-edit contacts on medic-conf

### ISSUE THREAD

**Issue by IreneAchola** [medic/medic-conf#297]
The support team normally gets requests to bulk-edit contacts, to add one or many attributes. We use custom python/NodeJS and other bash scripts that we've developed to automate these tasks, which include;

- Updating supervisors (which includes moving supervisor branches) and CHWs.
- Tagging CHWs on a new workflow so that forms may be shown based on the CHW tag added to their documents.
- Bulk deleting CHWs that have been wrongly uploaded.
- Adding partner-specific attributes to specific docs e.g. external_id that may not have been added during the user creation process.

We're essentially looking to replace the different scripts used by the team, to enhance medic-conf and to have a central and standardized way to update documents.

 cc @rosteve @kennsippell @dianabarsan

**Comment by dianabarsan** [comment]
Ready for AT on `rosteve:193-create-users`

**Comment by ngaruko** [comment]
Maybe this branch need to be rebased @rosteve @dianabarsan ?
Getting an error when trying to run `medic-conf` version of the branch...
![image](https://user-images.githubusercontent.com/6979995/79280398-5e7bf480-7f04-11ea-8561-e3b09760a373.png)

**Comment by rosteve** [comment]
Yup, it needed to be rebased. @ngaruko I've now rebased it and should be okay

**Comment by ngaruko** [comment]
Thanks @rosteve . Now I have been testing this from `cht-core/config/default` and I am getting the error below. Am I missing something in the folder:
```
ERROR TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at toSafeJson (/Users/bede/Medic/steve-medic-conf/src/fn/csv-to-docs.js:192:18)
    at /Users/bede/Medic/steve-medic-conf/src/fn/csv-to-docs.js:197:21
    at Array.map (<anonymous>)
    at toSafeJson (/Users/bede/Medic/steve-medic-conf/src/fn/csv-to-docs.js:193:16)
    at /Users/bede/Medic/steve-medic-conf/src/fn/csv-to-docs.js:197:21
    at Array.map (<anonymous>)
    at Object.toSafeJson (/Users/bede/Medic/steve-medic-conf/src/fn/csv-to-docs.js:193:16)
    at saveJsonDoc (/Users/bede/Medic/steve-medic-conf/src/fn/edit-contacts.js:17:89)
    at Array.map (<anonymous>) 
```

**Comment by ngaruko** [comment]
Looks good.
![image](https://user-images.githubusercontent.com/6979995/79543114-fc2c1b00-80e0-11ea-87d1-8abce215bf9d.png)

Can you please merge and close the issue @dianabarsan ? Thanks

**Comment by ngaruko** [comment]
Raised a different issue  #315  and assigned to @rosteve ... since this bug is not in this particular function we are testing atm.
Feel free to merge this one @dianabarsan when you are ready.

**Comment by dianabarsan** [comment]
Merged into `master`.
