### ISSUE TITLE
upload-app-forms skips the upload of forms based only on local changes, ignoring the state of the form on the instance

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#303]
Feature #113 was intended to perform a three-way diff between "current file", "last uploaded file", and "actual file on the instance". Currently a user can attempt to upload a form, but that upload can be skipped even when the form they are uploading is different than the form on the instance.

Forms should not simply be skipped over when uploading. This poses a risk to deployments in production, since what gets deployed does not align with what a user expects to deploy.

To reproduce: 
We will use two configuration folders to simulate two users deploying different versions of the configuration from their own machines.

1. `rm -Rf cht-core/config/default/.hashes` - Simulate a "fresh" new config for a clean repro
1. `cp -r cht-core/config/default cht-core/config/default2` We will use two configuration folders to simulate two users deploying different versions of the configuration from their own machines.
1. Make a change to the delivery form in `cht-core/default2`
1. `~/cht-core/config/default$ medic-conf convert-app-forms upload-app-forms --local -- delivery` "user 1" uploads the form 
1. `~/cht-core/config/default2$ medic-conf convert-app-forms upload-app-forms --local -- delivery` "user 2" uploads the same form and overwrites it
1. `~/cht-core/config/default$ medic-conf convert-app-forms upload-app-forms --local -- delivery` "user 1" sees there form isn't on the instance, and desires to upload it again

**Expected**
User 1 is uploading a form which is not on the instance
The user should be prompted to overwrite

**Observed**
The form is skipped
`INFO Form /home/kenn/webapp/config/default/forms/app/delivery.xml not uploaded, no changes`

**Comment by garethbowen** [comment]
Ready for AT in `301-check-properties-too`

This branch fixes: #271 #300 #301 #303 #306 so AT them at the same time.

**Comment by ngaruko** [comment]
LGTM 
![image](https://user-images.githubusercontent.com/6979995/78744292-50365180-79b5-11ea-8e90-86c9b9e67343.png)
