### ISSUE TITLE
Allow for configuring xml2sms in forms

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-conf#306]
In CHT Core 3.5.0 we added a feature for [compiling xforms into SMS messages](https://github.com/medic/cht-core/issues/4812) by defining a `xml2sms` on the form doc but medic-conf was not updated to allow for configuring this field.

**Comment by garethbowen** [comment]
Ready for AT in `301-check-properties-too`

This branch fixes: #271 #300 #301 #303 #306 so AT them at the same time.

AT instructions: make sure you can specify the `xml2sms` property in the forms `.properties.json` file and the doc in the database has the property set.

**Comment by ngaruko** [comment]
LGTM.
Back to you @garethbowen for a merge!
