### ISSUE TITLE
Missing optional appliesIf attribute on contact summary cards causes crash

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#322]
Documentation [shows](https://github.com/medic/medic-docs/blob/master/configuration/developing-community-health-applications.md#cards) cards.appliesIf as being optional. If it is missing, the contact summary fails to render.

`Configuration error in contact-summary function: card.appliesIf is not a function`

**Comment by MaxDiz** [comment]
@kennsippell can I move this over to medic-docs?

**Comment by kennsippell** [comment]
@MaxDiz The appliesIf attribute is documented as being optional but the current behavior is that it is required. I'd prefer to track it as a bug fix (the documented behavior seems appropriate). It may be possible that we decide to make it required - in which case we can update the documentation. Let's keep it a bug for now?

**Comment by garethbowen** [comment]
@kennsippell I guess it should default to `true`?

**Comment by kennsippell** [comment]
@garethbowen I believe true is the default for tasks, targets, and fields.

**Comment by dianabarsan** [comment]
Ready for AT on `322-appliesIf-defaults-to-true`

**Comment by newtewt** [comment]
@garethbowen  feel free to close this. I'm seeing this work without `appliesIf` defined, as a function, and as a bool.

**Comment by garethbowen** [comment]
Merged.
