### ISSUE TITLE
upload-app-forms and upload-contact-forms skip the upload on properties.json changes

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-conf#335]
We have an algorithm that prevents forms from being uploaded when no changes were made. Unfortunately, changes to the `properties.json` files are overlooked by this algorithm and a change in the actual xml is necessary to get a form updated.

**Comment by garethbowen** [comment]
I think this is the same bug as #301 - is that one not yet fixed?

**Comment by dianabarsan** [comment]
Oh no.... I think you're right and I was somehow running an older version of medic-conf. sorry! closing.
