### ISSUE TITLE
Convert CI from travis to GitHub Actions

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-conf#367]
**Describe the issue**
We've been using TravisCI reliably but they seem to be winding down the free tier with very long queue times and laying off many of their engineers. We should look to switch in the near future.

**Describe the improvement you'd like**
Switch to GitHub Actions and report anything you've learned on this issue.

**Describe alternatives you've considered**
We've compared with other CI providers [in this doc](https://docs.google.com/document/d/1UsMUk8qELddsyapA_hK8r_QYaxuEKbKEhcmcEkiIxwE/).

**Comment by andy5995** [comment]
Related comment on https://github.com/medic/cht-core/issues/6761#issuecomment-739435632

**Comment by garethbowen** [comment]
Merged. Thanks @newtewt !
