### ISSUE TITLE
Unable to hide fields using hidden_fields in properties.json

### ISSUE THREAD

**Issue by bindugowrig** [medic/medic-conf#376]
**Description:**Unable to hide fields in reports while using "hidden_fields" in properties.json 

**Attachments:**
![hidden_fields](https://user-images.githubusercontent.com/73226533/108897012-a0ed8200-763b-11eb-9c1b-54f46f67a71a.png)

**Comment by garethbowen** [comment]
Closing as this was resolved as discussed on [the forum](https://forum.communityhealthtoolkit.org/t/unable-to-hide-fields-in-reports-while-using-hidden-fields/1146).
