### ISSUE TITLE
Incorrect warning when specifying hidden_fields

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-conf#377]
**Describe the bug**
When I specify "hidden_fields" the console outputs a warning...

```
WARN Ignoring unknown properties in [filename]: hidden_fields
```

This is a known and supported field so the warning is incorrect. The field appears to work as expected.

**To Reproduce**
1. Modify the default `cht-core/config/default/forms/app/undo_death_report.properties.json` file to have `"hidden_fields": ["undo"]` which should hide the `undo` property in submitted forms
2. Execute `medic-conf <instance> convert-app-forms upload-app-forms` in the `cht-core/config/default` directory
3. Submit an Undo Death Report report

**Expected behavior**
- No warning shown in the console.
- The undo_death_report form is uploaded.
- The submitted report has the `undo` field hidden.

**Environment**
- Instance: localhost
- Client platform: Linux
- medic-conf version: latest
- cht-core version: latest

**Comment by garethbowen** [comment]
Ready for AT in medic-conf `377-remove-incorrect-warning`

**Comment by newtewt** [comment]
@garethbowen just to confirm I understand. The `WARN` displays when running the medic-conf command and then on the server the undo death report properties does not have the hidden fields. The behavior when using `377-remove-incorrect-warning`.  The error is no longer there, the doc has that property, and our app then hides it.

**Comment by garethbowen** [comment]
Right! medic-conf was warning that the field was unsupported but then using the field correctly later on anyway.

**Comment by newtewt** [comment]
ok cool! This is ready to merge and close.
