### ISSUE TITLE
Contacts with hardcoded types that also have a `contact_type` property don't get the correct contact_summary fields and don't count towards target goals

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-conf#382]
**Describe the bug**
If you have a contact that has a hardcoded type, like `person` or `clinic`, but they also have a `contact_type` property, their `contact_type` property will be evaluated as the actual contact type in some cases, instead of their type. 

These cases include: 
- displaying contact-summary fields or cards
- counting these contacts towards target goals

**To Reproduce**
1. Deploy default config.
2. Login with an offline user.
3. Create a new person that was born this month. Sync. Make sure sentinel processes the doc. Sync again.
4. Check that you see the `Medic ID` and `Age` contact summary fields. 
4. Check the targets page and see that you have a count of 1 for "Live births". 
5. Open the contact doc in Fauxton and add a field called `contact_type` and set the value to `something` (any string will work here, as long as it's not `person` :D )
6. Sync with the offline user. Check the targets page again and notice that "Live births" shows a count of 0. 
7. Open the contact page again, and see that you don't get the `Medic ID` or the `Age` contact summary fields anymore. 

**Expected behavior**
The contact should still count towards the target goal and the same contact-summary fields and cards should be displayed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/110738296-b10a8180-8237-11eb-8f6b-c58158e0b529.png)

**Environment**
- medic-conf version: 3.3.0
- cht-core version: 3.10, 3.11

**Additional context**
This is caused by an inconsistency when determining a contact's type, where we sometimes prioritize the `contact_type` field over the `type` field, when we should only use the `contact_type` field when the `type` is equal to `contact` - so when using configurable hierarchies.

**Comment by dianabarsan** [comment]
Ready for AT on `382-consistent-contact-type`

**Comment by newtewt** [comment]
Tested targets with contacts that had a no contact_type, a contact_type that is not in the list of custom contact types, and a valid custom contact type. They all are being contacted in targets now. 

This can be merged @dianabarsan

**Comment by dianabarsan** [comment]
Thanks @newtewt ! Merged to `master`.
