### ISSUE TITLE
Can't upload-app-settings on Node lower than 12

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-conf#387]
**Describe the bug**
Running Node 10, for example, and trying to run the `upload-app-settings` action, you'll get an error about `Promise.allSettled` not being a function. 

**To Reproduce**
1. Install latest `medic-conf`. Make sure you're using Node < 12. 
2. Take any config, any server. 
3. Run `upload-app-settings`
4. See `TypeError: Promise.allSettled is not a function`. 

**Expected behavior**
`upload-app-settings` should not fail. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/111334712-78760800-867c-11eb-84b3-5013d343a589.png)

**Environment**
- medic-conf version: 3.4.1

**Additional context**
It looks like we have no tests at all for `upload-app-settings`, as this should have failed the test suites for Node 8 and 10, which we should be supporting.

**Comment by dianabarsan** [comment]
Ready for AT on `387-node-8-support`. For AT, a basic smoke test should be ok, incl working with various instances (URL parsing was changed), also testing when used older node versions.

**Comment by ngaruko** [comment]
LGTM - Tested on local -VM (node v8.17.0) 

1. Checked out cht-core and cd to default config
2. checked medic-conf master
3. Ran `node medic-conf/src/bin/medic-conf.js` 
4. Observed error is in the description above
![image](https://user-images.githubusercontent.com/6979995/112230893-92c26e00-8c9a-11eb-85ac-57c158318f77.png)

5. Checked out remote branch `387-node-8-support`
6. Ran `node medic-conf/src/bin/medic-conf.js` 
7. App settings uploaded with no errors, but a warning - that I think is not related to this ticket
![image](https://user-images.githubusercontent.com/6979995/112230826-70c8eb80-8c9a-11eb-853c-8bdb3c29f0ec.png)

**Comment by garethbowen** [comment]
@ngaruko Is this ready to merge?

**Comment by ngaruko** [comment]
@garethbowen Yes. I was testing with more versions, like 10.24.0 and doing smoke tests on different instances.

**Comment by garethbowen** [comment]
Merged.
