### ISSUE TITLE
Track usage

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-conf#391]
**Is your feature request related to a problem? Please describe.**
We don't really have good data on how medic-conf is being used.

**Describe the solution you'd like**
Track usage so we can see how people are using the CLI and how it's working for them.

**Describe alternatives you've considered**
Just ask them.

**Additional context**
- This isn't trivial because currently we have no local storage or remote server to collect the data.
- Don't collect data without getting permission.

**Comment by kennsippell** [comment]
Close https://github.com/medic/medic-conf/issues/298 as dupe?

**Comment by garethbowen** [comment]
Actually I prefer your version! Closing this one.
