### ISSUE TITLE
Form validation throw exception when medic-conf has --archive attibute

### ISSUE THREAD

**Issue by latin-panda** [medic/medic-conf#396]
**To Reproduce**
Steps to reproduce the behaviour:
1. Make sure you don't have api running.
2. Run medic-conf with `--archive` attribute. One way is to install medic-conf 3.5.0 in cht-core, and run `grunt default`. See [here](https://github.com/medic/cht-core/blob/8f328d40b21dd95a6f24606e19c607c75e8dc41d/Gruntfile.js#L579).
2. Exception are logged in console because of [this request](https://github.com/medic/medic-conf/blob/92b7a6f9da1ab7add6469eb5f636ef7bd0571fa2/src/lib/api.js#L116).

**Expected behavior**
If api isn't running and the `--archive` attribute is present then don’t validate the form and assume the form is correct. 

**Screenshots**
<img width="790" alt="Screen Shot 2021-04-20 at 4 18 35 pm" src="https://user-images.githubusercontent.com/66472237/115384123-dc9e6580-a200-11eb-963f-0ee544830f7a.png">

**Environment**
- Instance: local
- Client platform: MacOS
- medic-conf version: 3.5.0 
- cht-core version: 3.11

**Additional context**
I noticed that [getApiUrl](https://github.com/medic/medic-conf/blob/e2c3103d17a051aa3c41f98682cf72cb88e8cd41/src/lib/get-api-url.js#L16) is adding the '--archive mode'. Not sure the original intention but because of the function name, it could lead to this type of errors in the future, since that’s not an url. Maybe that needs a fix as well, like using a separate check for archive and leaving the function just returning API's url or undefined accordingly.

**Comment by latin-panda** [comment]
Note, this is blocking the upgrade of medic-conf (3.2.1 to 3.5.0) as dependency in cht-core.

**Comment by mrsarm** [comment]
Another similar issue also happens in older versions of medic-conf (tested with v3.4.1) using the `--archive` argument, it shows error when the user doesn't have an API running, and it shows a wrong URL but the root cause is not the URL malformed but a local API is not running:

```diff
...
INFO Starting action: upload-resources… 
INFO Configuration upload complete! 
- ERROR Error trying to get couchdb config: RequestError: Error: Invalid URI "null//null@null/api/couch-config-attachments" 
INFO upload-resources complete. 
...
INFO Translation /projects/medic/cht-core/config/default/translations/messages-en.properties uploaded 
- ERROR Error trying to get couchdb config: RequestError: Error: Invalid URI "null//null@null/api/couch-config-attachments" 
INFO upload-custom-translations complete. 
...
```

**Comment by mrsarm** [comment]
Ready for AT, PR https://github.com/medic/medic-conf/pull/397 , branch `396-xforms-validations-archive-mode`.

First, some clarifications pointed [here](https://github.com/medic/medic-conf/pull/397#issuecomment-827140562) in the PR:

> - Archive mode is only used by grunt in the task build-config at Gruntfile.js#L579, that is executed by default when pushing the first settings and the webapp assets to the CHT during development.
> - I confirmed with Kenn that is not used by Apps developers in any other way.
> - The task does not perform the upload, just the creation of the resources in a temporal folder that is pushed to the CouchDB later, so --archive mode shouldn't connect with the DB or the API in any way, but because a bug, it was doing that, and because a bug in the XForm validations, the validations were also trying to connect with the API in that mode.


To summarize, the PR addresses some concrete bugs and were added some refactors to avoid potential bug in the future, so check that other workflows were not affected and continue to work as before should be tested.

To test that `--archive` mode works as expected (without logging errors and without connecting to the API or the DB), I recommend to check the following:

1. Go to the [config/default](https://github.com/medic/cht-core/tree/master/config/default) folder of your local CHT.
2. Make any change in a form (like change the label of one of the fields), and execute something like `medic-conf --archive --destination=/some/temp/path` while the DB is up and the API is running.
3. During the execution, you shouldn't see any new request recorded in the DB logs or the API logs.
4. Sign-in with any user in the CHT and sync the data, then go to the option to create a report with the form changed in the step 2. The changes made to its source code shouldn't be reflect in the app.
5. Also the folder passed to the `--destination` argument should contain the compiled forms.

The same steps can be executed but with the DB and the API down, and no errors in the medic-conf output should appear.

To test that the normal workflow `medic-conf --local` continue to work like before, the steps are similar, but when opening the form report in the webapp, you should see reflected the changes made in the source code, and ensure no errors are shown in the logs of either medic-conf, the API or the DB during the syncronization.

**Comment by ngaruko** [comment]
Thanks @mrsarm for details on how to AT.
Tested on local, with `node ../../../medic-conf/src/bin/medic-conf.js --archive --destination=./archived-forms`. On `medic-conf master`, errors as expected 
![image](https://user-images.githubusercontent.com/6979995/117103649-d8607380-adce-11eb-8584-bf444d98c5fb.png)
but on the branch, no errors and the folder is created with the docs
![image](https://user-images.githubusercontent.com/6979995/117103750-00e86d80-adcf-11eb-9617-4880a5adeb83.png)

Good to merge 👍
