### ISSUE TITLE
Unable to calculate "index of event" in modifyContent function

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#398]
**Describe the bug**
Very commonly, CHT configurations have some sort of "assessment" and then some scheduled "follow-up tasks".
Some of these follow-ups (less common, but used by Muso), need to know "is this the first followup?" or the 3rd? or the 5th? (event index of followup)
Thus, the tasks's modifyContent function (controlling data passed from task to form) [calculates the index of the event being clicked on](https://github.com/medic/config-muso/blob/master/tasks.extras.js#L46).

In < cht-core v3.8, the modifyContent is invoked at the time the user clicks on the task. Therefore the calculation of "what event is being clicked on" can be calculated using Utils.now...

```
  const now = Utils.now().getTime();
  return events.findIndex(event => {
    const dueDate = event.dueDate(event, contact, report);
    const days = event.dueDate ? 0 : (event.days || 0);
    const lowerBound = Utils.addDate(dueDate, days - event.start);
    const upperBound = Utils.addDate(dueDate, days + event.end + 1);
    return now >= lowerBound.getTime() && now < upperBound.getTime();
  });
```

In >= cht-core v3.8, the result of modifyContent is cached when the task document is created. It is now invalid to use Utils.now in the modifyContent function - the Utils.now function means a different thing! From the [3.8 release notes](https://github.com/medic/cht-core/blob/master/release-notes/docs/3.8.0.md): 

> A task's content is cached inside the task document. Any timestamps or calculation can be up to seven days old. This is a breaking change for configurations using the current time as part of their calculations.

In the post v3.8 world - the modifyContent function doesn't have enough information to know which event is currently "having its content modified". The event index seems to now be impossible to reliably calculate.

**Proposed Solution**
Update modifyContent interface to accept parameter `event` - which is the specific task event being modified.

**To Reproduce**
1. Deploying Muso configuration https://github.com/medic/config-muso
2. Complete an assessemnt for patient under 5 resulting in treatment of malaria https://github.com/medic/config-muso/blob/master/test/form-inputs.js#L167
3. View the tasks tab on the same day (creates follow-up task documents with calculated content)
4. Advance system clock + 3 days.
5. Complete follow-up and view resulting report (inputs.t_follow_up_count)

Expected value of `t_follow_up_count` = 3
Observed value of `t_follow_up_count` = 0

**Logs**
You can see this reproducing frequently in the data for Muso:  https://github.com/medic/config-muso/issues/241 resulted in https://github.com/medic/config-muso/issues/270.

**Screenshots**

**Environment**
- Instance: muso-mali.app
- cht-core version: >= v3,8

**Additional context**
This bug seems minor, but in reality it affects referrals and drug treatment recommendations in a production application.

**Comment by dianabarsan** [comment]
@kennsippell 
If I'm reading this correctly, you'd like the event index (or event itself) to be passed here
https://github.com/medic/medic-conf/blob/master/src/nools/task-emitter.js#L145 
and forwarded as a parameter to `modifyContent` here:
https://github.com/medic/medic-conf/blob/master/src/nools/task-emitter.js#L154

So `modifyContent` gets the fourth parameter with the whole event definition ( https://github.com/medic/medic-conf/blob/master/src/lib/validate-declarative-schema.js#L85 ) or more information is necessary for the correct calculation?

**Comment by dianabarsan** [comment]
> Proposed Solution
Update modifyContent interface to accept parameter event - which is the specific task event being modified.

This works well, as expected :) But the final code depends on whether we pass an event id or the event itself to the `modifyContent` function, so waiting for that piece of feedback before a PR.

**Comment by abbyad** [comment]
I think I understand the issue in theory, but curious why the `t_follow_up_count` would be expected to be 3 rather than 0 (or 1?) in this case. I would have expected the `follow_up_count` to be independent of the date of completion, but I'm likely missing something!

**Comment by kennsippell** [comment]
@dianabarsan I'd probably do the event itself. That is consistent with other interfaces like resolvedIf which is passed the same.

> why the t_follow_up_count would be expected to be 3 rather than 0 (or 1?) 

@abbyad In the scenario given, there are daily treatment follow-ups: 24hr, 48hr, 72hr.  So if you wait 3 days, you're doing the 72hr follow-up. I'm not sure why, but Muso uses a 1-base index and not a 0-base index. So epected value is 3 (72hr follow-up), but the current behaviour is 0 (an undiscovered index).

**Comment by abbyad** [comment]
Ah, thanks for the explanation. I remember using `t_follow_up_count` for our early CHT app projects to count the number of submissions, not to identify which submission a report is.

Given this scenario, would it make sense to calculate which visit it is _in_ the form, based on the time of the previous triggering report?

**Comment by abbyad** [comment]
Nevermind, I think I get this now. Glad to see the improvement coming through quickly.

**Comment by kennsippell** [comment]
> Given this scenario, would it make sense to calculate which visit it is in the form, based on the time of the previous triggering report?

I think that's technically possible but this would require maintaining a duplicate of multiple task schedules in multiple forms. They end up being pretty long if-else ladders -- like maintaining this for the [anc followup](https://github.com/medic/config-muso/blob/master/tasks.js#L74)'s 27 events would be awkward to write and maintain.  Very nice to be able to pass (and test) this data cleanly without duplication.

**Comment by dianabarsan** [comment]
This is ready for AT on `398-pass-event-to-modify-content`. 

Tasks actions `modifyContent` functions now accept a new parameter, containing the current event definition. 
The muso config also required changes to make use of the new parameter, so please check out this PR: https://github.com/medic/config-muso/pull/272

Documentation PR: https://github.com/medic/cht-docs/pull/481.

**Comment by dianabarsan** [comment]
For minimal AT, please check out `config-muso` and apply the changes from this PR: https://github.com/medic/config-muso/pull/272 . 
Deploy the config and follow the reproduction steps in the issue description. 
One thing to mention is that in step (3) (View the tasks tab on the same day (creates follow-up task documents with calculated content) - I didn't see an additional task pop up, I had to turn my system clock ahead one day to get a task. 
The result should be that the resulting followup form calculates the correct `t_follow_up_count` (depending on which day you submitted the followup). 

For more granular AT, you should create a new task with an action that uses the `modifyContent` function and has multiple events. Use the new event param in `modifyContent` to add some data to the form. 
Upon task submission, the resulting report should have the correct event sourced value. 

@ngaruko please tell me if you need additional assistance with the minimal config.

**Comment by ngaruko** [comment]
Thanks @dianabarsan . I was able to reproduce it but as mentioned, for some reason, tasks do not fire up directly. But the `t_follow_up_count` updates nonetheless. Not sure if it is something in the form @kennsippell (ie the task needing a change of system clock to display) and/or if we should NOT worry about this with this PR?
![image](https://user-images.githubusercontent.com/6979995/115976032-f3a4d500-a5bd-11eb-9418-9b64f7cfa539.png)

**Comment by dianabarsan** [comment]
> tasks do not fire up directly
I think that's a miscommunication about how the config should work or a problem in the config itself, it's not related to this change.

**Comment by dianabarsan** [comment]
Merged into `master`
