### ISSUE TITLE
Handle derivative configs

### ISSUE THREAD

**Issue by abbyad** [medic/medic-conf#45]
We have 10+ Standard projects using the same base configuration that gets updated whenever fixes or new features are added to the Standard config. Typically the different Standard projects have slight modifications to the Standard config, such as `locale_outgoing`, `default_country_code`, and `gateway_number`, and we do not want to override these when pushing an updated Standard config.. 

Manually maintaining the modifications for Standard projects is very error prone and important changes can get lost with updates. To avoid this situation we have been using a _child_ `settings.json` which refers to a _parent_ `app_settings.json`. We have a [script](https://github.com/medic/medic-projects/blob/2d31bbf0deb2e7186bddda3a37e7f3b5e62999a8/scripts/settings.js) that then generates the app_settings for the child project accordingly. We should include a reliable way to do this within medic-config to get rid of one of the last separate config scripts still in use. This is a good time to review and improve the process if possible.

----------------------
Excerpt of usage in the [settings.js script](https://github.com/medic/medic-projects/blob/2d31bbf0deb2e7186bddda3a37e7f3b5e62999a8/scripts/settings.js) related to the child `settings.json`:
```
Structured like app_settings.json, and copied into the parent settings.
Additionally, special fields can be used:
  _parent  path to parent app_settings into which these settings will be merged
  _forms   array of forms to include. All others will be removed. Because the
                merge into the parent settings uses a deep copy it is not possible
                to remove fields. Setting which forms to use allows a future proof
                way to specify the forms to include in the final app_settings.
```

Here is an [child setting file](https://github.com/medic/medic-projects/blob/14b7479a1c3d0911e4bebca0c863d051badfd377/tts-indonesia/settings.json) which specifies the forms in use, so that forms for other use cases are not shown in the reports filter`*`:
```
{
  "_parent": "../standard/app_settings.json",
  "_forms": [
    "N",
    "P",
    "V",
    "D",
    "F",
    "OFF",
    "ON"
  ],
  "locale_outgoing": "id",
  "default_country_code": "62",
  "gateway_number": "+62812_______",
  "district_admins_access_unallocated_messages": true,
  "outgoing_deny_list": "3636, 1166, 98888, TELKOMSEL"
}
```

`*` it could be better to add context to JSON forms so that they can be hidden from the Reports tab filter accordingly.

**Comment by alxndrsn** [comment]
Where should `tasks.json`, `targets.json`, `contact-summary.js` and `rules.nools.js` come from?  the parent dir or the child?

**Comment by abbyad** [comment]
Allowing for taking those from the child does make sense. That said, so far we haven't had any different ones so we don't absolutely need to support that now. What do you think is the best approach given the way medic-conf is set up?

**Comment by alxndrsn** [comment]
How does this look?  File called `settings.inherit.json`, which defines `.parent` - the directory in which `app_settings` etc. are located, and `app_settings` - properties to override in `app_settings`.
```
{
  "parent": "../parent",
  "app_settings": {
    "from_child": true,
    "overridden": true
  }
}
```

It's not 100% clear from examples if app_settings values should be directly overwritten, or if these values should be additive.  I understand from the ticket that they are additive in the current implementation, but I wonder if this is necessary - I think it could be clearer if the values are directly overridden, and we wouldn't then require special handling for `forms`.

**Comment by abbyad** [comment]
I'll follow up about the format to better understand it. The separate handling for forms allows you to just state the names of the forms you want but without defining the structure. This makes it easy to update the form definition once in the parent settings and have that propagate to all child configs.

**Comment by alxndrsn** [comment]
It currently looks like that it will include any forms listed in the child that _also_ exist in the parent.  If you list something non-existent in the child, it will be silently ignored...

**Comment by abbyad** [comment]
Works well! Tested by using the `compile-app-settings` action on a a child settings converted to the new `settings.inherit.json` format:

```
{
  "inherit": "../standard",
  "replace": {
    "district_admins_access_unallocated_messages": true,
    "locale_outgoing": "hi",
    "default_country_code": "91",
  },
  "merge": {
  },
  "delete": [
    "_id"
  ],
  "filter": {
    "forms": [
      "N",
      "P",
      "V",
      "D",
      "F",
      "OFF",
      "ON"
    ]
  }
}
```

Leaving open until we document accordingly in Readme. @alxndrsn is that something you can add or do you want me to do that?

**Comment by alxndrsn** [comment]
Docs added to `README`!
