### ISSUE TITLE
Ability to delete individual forms

### ISSUE THREAD

**Issue by abbyad** [medic/medic-conf#53]
When creating forms to test an issue or feature I upload the form via medic-conf and then removing it via futon. Now that we have to do a SSH tunnel to access futon it's more of a hassle to remove a single form. Via medic-conf the only option right now is to `delete-all-forms` and then re-upload them all previous forms. It would be nice if we could delete a single form from an instance instead. For example, using `delete-*-forms -- form_name`, similar to how we can use `upload-*-forms -- form_name`.

**Comment by alxndrsn** [comment]
Available in version `1.10.0`.
