### ISSUE TITLE
upload-resources fails due to hidden files

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-conf#63]
I keep getting this error when I try to upload-resources. It's a file that OSX generates automatically but it trips up upload-resources and it's quite annoying. I have to delete the file and then run the command again very quickly before the OS regenerates the file. Can we make sure these files are ignored by medic-conf?

![image](https://user-images.githubusercontent.com/1286381/37675843-8c87d8f6-2c33-11e8-81af-fd9dcab553d8.png)

**Comment by browndav** [comment]
That's MacOS X Finder metadata. Suggest we use `glob` to match and ignore dotfiles.

**Comment by alxndrsn** [comment]
Fixed in `1.11.7`.

**Comment by sglangevin** [comment]
Thank you!
