### ISSUE TITLE
Reject console.log() statements in tasks, targets, contact-summary IN PROD ONLY

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-conf#72]

**Comment by kennsippell** [comment]
In medic-conf 3.0, we introduced default eslint rules which disallow `console` and `debugger` statements.  Users have the option to use the `-- --debug` flag to use these commands temporarily during development, however it should not be used in production.  Although this requirement hasn't been implemented as described, I feel the tooling we have in place today makes further investments here unjustified. Please re-activate if you disagree.
