### ISSUE TITLE
Task date not correct when associated to first `scheduled_task`

### ISSUE THREAD

**Issue by abbyad** [medic/medic-conf#73]
If a task is created based on the first `scheduled_task` the date will be the `reported_date` instead of basing it on the `scheduled_task`'s due date.

**Comment by abbyad** [comment]
This seems to be because the 0 index for `scheduledTaskIdx` mistakenly skips down to the else block here: https://github.com/medic/medic-conf/blob/f8c13239e14c7ec1979fb5c48e68797ce0f627e4/src/lib/compile-nools-rules.js#L83-L89

**Comment by alxndrsn** [comment]
Good spot, thanks!
