### ISSUE TITLE
Add support for contacts and reports for all Nools workflows

### ISSUE THREAD

**Issue by abbyad** [medic/medic-conf#74]
With the new style of config we currently support Tasks for reports, and Targets for reports and people. We need to add support for Targets about places, and Tasks about any person or place.

### Tasks
Does not yet support people or places.

| property | description | required |
|---|---|---|
| `appliesToForms` | array. The form codes for which this task should be associated. | no |
| `appliesToScheduledTaskIf` | function(report,index). If present, associate the task to the report's scheduled_task elements for which the function returns true. | no |
| `appliesIf` | function(contact, report). Create the task only if this function returns true. | no |

### Targets
Does not yet support places. Places have type `clinic`, `health_center`, or `district_hospital`, which may be expanded with flexible hierarchies.

| property | description | required |
|---|---|---|
| `appliesToType` | `'report'`, `'person'`, `'place'`. Currently only supports `'report'` and `'person'`. | yes |
| `appliesToForms` | array. The form codes for which this target should be associated. | yes, if `appliesToType` is `'report'` |
| `appliesIf` | function(contact, report). Create the target only if this function returns true. | no |

## Proposal A
Create a new property to differentiate between reports and contacts, then use a common property to differentiate further. Scheduled tasks would continue to be handled separately as they are now.

| property | description | required |
|---|---|---|
| *`appliesTo`* | What the task/target item applies to... either `contacts` or `reports` | yes |
| *`appliesToType`* | Array of report or contact types. Eg `['pregnancy', 'P']`, `['clinic', 'district_hospital']`, `['person']` | no |
| `appliesToScheduledTaskIf` | function(report,index). If present, associate the task to the report's scheduled_task elements for which the function returns true. | no |
| `appliesIf` | function(contact, report). Create the task only if this function returns true. | no |

## Proposal B
Similar to proposal A but differentiating `scheduled_tasks` at the top level, and then using a common `appliesIf` instead of a separate `appliesToScheduledTaskIf`.

| property | description | required |
|---|---|---|
| *`appliesTo`* | What the task/target item applies to... either `contacts`, `reports`, or `scheduled_tasks`. | yes |
| *`appliesToType`* | Array of report or contact types. Eg `['pregnancy', 'P']`, `['clinic', 'district_hospital']`, `['person']` | no |
| `appliesIf` | function(contact, report, scheduledTaskIndex). Create the task or target instance only if this function returns true. `scheduledTaskIndex` will be null for `contacts` and `reports` | no |

I think Proposal A is a closer extension of what we currently have, but figured I'd put Proposal B out there since it may be clearer to configurers. Which would you prefer @derickl, @ngamita, @sglangevin?

**Comment by alxndrsn** [comment]
Proposal B looks much more usable to me.

**Comment by alxndrsn** [comment]
I've added tests around the current nools code, which should make it clearer what the current code is doing, and less risky to change it.

**Comment by alxndrsn** [comment]
I think this can be closed.  Pleased open individual tickets if some parts of this still need implementation.
