### ISSUE TITLE
Update to work with settings change in web app

### ISSUE THREAD

**Issue by newtewt** [medic/medic-conf#75]
Web app settings were moved to their own ddoc. medic-conf needs updated to work with these changes. An error is shown when trying to backup the current settings.

ERROR:
`ERROR Error: Failed to fetch existing app_settings from http://admin:****@localhost:5984/medic/_design/medic/_rewrite/app_settings/medic.
      Check that medic-api is running and that you're connecting on the correct port!
    at request.catch.err (/Users/ewt/.nvm/versions/node/v8.11.3/lib/node_modules/medic-conf/src/fn/backup-app-settings.js:17:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

LOG:
```
INFO Using instance URL from COUCH_URL environment variable.
INFO Processing config in localhost-config for http://admin:****@localhost:5984.
INFO Actions:
     - compile-app-settings
     - backup-app-settings
     - upload-app-settings
     - convert-app-forms
     - convert-collect-forms
     - convert-contact-forms
     - backup-all-forms
     - delete-all-forms
     - upload-app-forms
     - upload-collect-forms
     - upload-contact-forms
     - upload-resources
     - upload-custom-translations
     - csv-to-docs
     - upload-docs
INFO Extra args: undefined
INFO Current version: 1.17.8.  Checking NPM for updates…
INFO You are already on the latest version :¬)
INFO Starting action: compile-app-settings…
WARN No package.json file found.  This project may be missing tests, or improperly set up.
WARN Project has no dependency on medic-conf.  It may not have any tests.
WARN tasks.json file is deprecated.  Please rename ./tasks.json to ./task-schedules.json
INFO compile-app-settings complete.
INFO Starting action: backup-app-settings…
ERROR Error: Failed to fetch existing app_settings from http://admin:****@localhost:5984/medic/_design/medic/_rewrite/app_settings/medic.
      Check that medic-api is running and that you're connecting on the correct port!
    at request.catch.err (/Users/ewt/.nvm/versions/node/v8.11.3/lib/node_modules/medic-conf/src/fn/backup-app-settings.js:17:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

https://github.com/medic/medic-webapp/issues/4541

**Comment by SCdF** [comment]
@garethbowen I added this directly to the 3.0.0 because it sounds like something we definitely need to fix before we go live (otherwise medic conf breaks!).

IDK if you want to close this and re-create it inside medic-webapp so it has the same flow etc as other things (as we have done in the past), or take advantage of projects now being org wide and have tickets in the repo they are about, linking everything together in projects.

**Comment by newtewt** [comment]
@garethbowen  @SCdF  This is because I was using medic-conf --local vs medic-conf --url http://admin:pass@127.0.0.1:5988. Not sure if --local is supposed to be for the API or database. Maybe this is no longer a bug but a documentation update.

**Comment by SCdF** [comment]
@newtewt `--local` should Do The Right Thing, and it's clearly not, so that's a bug regardless of what the right thing is.

While we're here, there is also probably a bug with remote installations because the admin user has been renamed to `medic`. We're going to have to support both old and new here as well, which may make things complicated

**Comment by garethbowen** [comment]
I'm removing this from 3.0.0 as it can be released separately, it doesn't affect production, and there is a working by using an explicit URL.

I'll look at patching this when I get back from to the keyboard next week.

**Comment by garethbowen** [comment]
Code review please @vimemo

**Comment by icm-marcelo** [comment]
Hello, I have the same problem on this one, it was like failed to fetch the existing app.

What do you recommend the solution on this?


Thanks
