### ISSUE TITLE
Compile-nools-rules jshint needs to allow scope 

### ISSUE THREAD

**Issue by newtewt** [medic/medic-conf#79]
Currently when using compile-nools-rules.js we are running jshint. Nools can take a scope object and make it available to the rules when executing. When trying to use the scope and running tests it fails because jshint thinks the object being used is not defined. We need a way to either account for them or add exceptions to jshint. I'll edit this issue once I've pushed an example branch to show the issue.

**Comment by SCdF** [comment]
Depending on the exact example you're talking about there is a section of jshint where you can define globals: https://stackoverflow.com/questions/17709657/how-to-tell-jslint-jshint-what-global-variables-are-already-defined

**Comment by newtewt** [comment]
Hmm, I'm not sure that the jshintrc works with the API version of JSHint but cannot find anything definitive on their docs about it. http://jshint.com/docs/. I've tried putting the jshintrc file a few different places with no luck, and the wording about `JSHint will start looking for this file in the same directory as the file that's being linted. If not found, it will move one level up the directory tree all the way up to the filesystem root.` seems to make me think it won't look for it the way medic-conf is going after it. Since we are passing a string into jshint instead of sending a file. I think an easy fix would be to add an argument that gets to the lint function and adds to the predef array we are already passing along. 

https://github.com/medic/medic-conf/blob/d6aafb21fea2a24a113731e08d6950b8551e5016/src/lib/compile-nools-rules.js#L9-L13

**Comment by alxndrsn** [comment]
@newtewt is this still a problem?  If so, please re-open the ticket along with the example.
