### ISSUE TITLE
Decide Medic-logs fate 

### ISSUE THREAD

**Issue by newtewt** [medic/medic-conf#82]
With 3.0 infrastructure medic-logs no longer works as is. There could be possible changes to the apps and medic-logs to make it work or possibly use centralized logging. 

Command used by medic-logs to pull logs
`rsync -az --progress -e 'ssh -p 33696' "vm@${domain}:${logPath}/*" "$localDir"`

@Hareet  @garethbowen

**Comment by garethbowen** [comment]
My understanding is it is essential that tech leads, developers, SREs, and QAa can get access to logs on production machines so this is a blocker for medic-webapp 3.0. @Hareet Is centralised logging realistic for the 3.0 release timeframe?

**Comment by alxndrsn** [comment]
:+1: See #82 for work towards supporting log access in webapp v3.
