### ISSUE TITLE
Use API_URL in preference to COUCH_URL

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-conf#86]
As per https://github.com/medic/medic-conf/pull/78, we now use `API_URL` instead of `COUCH_URL`.  Hack introduced in https://github.com/medic/medic-conf/pull/78/files should be removed and references to the `COUCH_URL` env var removed.  Also worth checking if `couchUrl` should be `apiUrl`.

**Comment by alxndrsn** [comment]
Wait for the outcome of this PR before deciding if this issue is still correct: https://github.com/medic/medic-webapp/pull/4906

**Comment by garethbowen** [comment]
Makes sense to me!

**Comment by alxndrsn** [comment]
`API_URL` no longer exists, so we will stick with `COUCH_URL`.

**Comment by garethbowen** [comment]
@alxndrsn I think it makes sense for medic-api to use COUCH_URL and medic-conf to use API_URL - obviously medic-api shouldn't refer to itself and medic-conf needs to use apis that are part of medic-api.

I think we should reopen this issue and remove the port hack so users can use whatever port they like.

**Comment by alxndrsn** [comment]
Use `API_URL` if available, if not, fall back on `COUCH_URL`.

**Comment by garethbowen** [comment]
As far as I can tell this is done - COUCH_URL is only used when installing locally.
