### ISSUE TITLE
add webapp v3 support for medic-logs

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-conf#89]
From #82:
> With 3.0 infrastructure medic-logs no longer works as is. There could be possible changes to the apps and medic-logs to make it work or possibly use centralized logging.

We will need to support this, or have an alternative platform (e.g. ELK or whatever) for accessing logs from dev/test and prod machines.

**Comment by garethbowen** [comment]
This requirement has been resolved by using logtrail.
