### ISSUE TITLE
Contact-based tasks do not work

### ISSUE THREAD

**Issue by derickl** [medic/medic-conf#93]
@alxndrsn 

From this https://github.com/medic/medic-conf/blob/bf033fa87fa1b4a43c4f45e046ed63ce65bafb17/src/nools/lib.js#L74, it appears we do not take into account triggering tasks based on contacts alone.

I've made a small change [here](4905f1d) (from @binokaryg insights) but not sure if it might break other thinks.

**Comment by alxndrsn** [comment]
Can you supply an example of config which doesn't work?  The link above doesn't work.

**Comment by derickl** [comment]
https://github.com/medic/medic-projects/tree/lg_ke_declarative_demo/lg-kenya

**Comment by derickl** [comment]
The change I made [here](https://github.com/medic/medic-conf/issues/4905f1d) ensures the task shows on the task bar. Unfortunately, clicking on the task only shows the task summary page rather than the desired form.

<img width="1232" alt="screenshot 2018-10-17 at 19 53 11" src="https://user-images.githubusercontent.com/83162/47122784-5aefaa80-d246-11e8-99f7-eb1735e7709a.png">

**Comment by garethbowen** [comment]
@derickl The summary page shows if you have zero or two or more actions. Can you check how many actions you have configured?

**Comment by derickl** [comment]
Just one @garethbowen using the new declarative style.

```
{
        icon: 'family',
        title: 'task.family_survey.title',
        appliesTo: 'contacts',
        appliesToType: [ 'clinic' ],
        appliesIf: function (c){
            return !isFormArraySubmittedInWindow(
                c.reports, 
                ['family_survey'], 
                Utils.addDate(new Date(), -180).getTime(), 
                Utils.addDate(new Date(),  0).getTime()
            );
        },
        actions: [ { form:'family_survey' } ],
        events: [ {
            id: 'family-survey',
            start:0, end:100, days:0,
            dueDate: getNextFamilySurveyDate  // function gets expected date of next family survey 
        } ],
        resolvedIf: function(c, r, event, dueDate) {
            return isFormArraySubmittedInWindow(c.reports, ['family_survey'],
                    Utils.addDate(dueDate, -event.start).getTime(),
                    Utils.addDate(dueDate,  event.end+1).getTime());
        },
    },
```

**Comment by derickl** [comment]
The change here https://github.com/medic/medic-conf/pull/97 get the task to show @garethbowen

**Comment by alxndrsn** [comment]
Released in `1.18.4`:
```
dueDate: function(contact, event),
```
or
```
event.days
```
Let me know if that works.

**Comment by derickl** [comment]
Hi @alxndrsn 

I only get the task summary screen (rather than the form) with the config above.

**Comment by derickl** [comment]
One more issue to bump up the queue @alxndrsn ?

Clicking on the task does not launch the form but rather displays an incomplete summary screen.
