### ISSUE TITLE
We need a way to explicitly specify where profile cards will be attached to.

### ISSUE THREAD

**Issue by derickl** [medic/medic-conf#95]
For fields, we explicitly specify which contacts will have the specified fields. Currently, we cannot explicitly specify this profile cards. We can get around this by adding extra checks in the `appliesIf` section.

**Comment by kennsippell** [comment]
@derickl Do you think this issue is still relevant?

**Comment by derickl** [comment]
Probably. I'll need to refresh my mind on the original issue.

**Comment by derickl** [comment]
I don't think the issue is now relevant since we have an `appliesToType` discriminator in contact card definition @kennsippell
